import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { canonicalizeJson, sha256Hex } from "../../scripts/digest-artifact.mjs";
import { generateRendererHandoff } from "../../scripts/generate-docs.mjs";
import { NODE_CODE_SAMPLES } from "../../scripts/node-code-samples.mjs";
import { validateRendererReport } from "../../scripts/verify-renderer-report.mjs";
import rendererAttestations from "../fixtures/release/renderer-attestations.json";
import {
  rendererHandoff as handoff,
  rendererHandoffSidecar as handoffSidecar,
  rendererHandoffSource as handoffSource,
  rendererReportFixture,
  validRendererReport,
} from "./renderer-report-fixtures.js";

const repositoryRoot = process.cwd();
const temporaryDirectories: string[] = [];

afterAll(() => {
  for (const directory of temporaryDirectories) {
    rmSync(directory, { recursive: true, force: true });
  }
});

describe("renderer report validation", () => {
  it("keeps the canonical handoff and its detached digest generated byte-for-byte", async () => {
    const generated = await generateRendererHandoff();

    expect(handoffSource.toString("utf8")).toBe(generated.source);
    expect(handoffSidecar.toString("utf8")).toBe(`${generated.digest}\n`);
    expect(handoff).not.toHaveProperty("digest");
    expect(handoff).not.toHaveProperty("sha256");
    expect(handoff.operations).toHaveLength(56);
    expect(handoff.operations.flatMap(({ samples }) => samples)).toHaveLength(56);
    expect(new Set(handoff.operations.map(({ operationId }) => operationId))).toHaveLength(56);

    for (const { operationId, samples } of handoff.operations) {
      const sample = NODE_CODE_SAMPLES[operationId];
      expect(sample, operationId).toBeDefined();
      expect(samples).toEqual([
        {
          label: sample?.label,
          language: sample?.lang,
          sourceHash: sha256Hex(Buffer.from(sample?.source ?? "", "utf8")),
        },
      ]);
    }
  });

  for (const testCase of rendererAttestations.cases) {
    it(testCase.name, () => {
      const fixture = rendererReportFixture(testCase.mutation);
      const validate = () =>
        validateRendererReport({
          handoffSource,
          handoffSidecar: fixture.handoffSidecar,
          reportSource: fixture.reportSource,
        });

      if (testCase.expectedError === null) {
        expect(validate()).toEqual({
          handoffDigest: sha256Hex(handoffSource),
          operations: 56,
          tabs: 56,
        });
      } else {
        expect(validate).toThrow(testCase.expectedError);
      }
    });
  }

  it("uses the importable validator from the CLI", () => {
    const directory = mkdtempSync(join(tmpdir(), "ahasend-renderer-report-"));
    temporaryDirectories.push(directory);
    const reportPath = join(directory, "renderer-report.json");
    writeFileSync(reportPath, canonicalizeJson(validRendererReport()));

    const result = spawnSync(process.execPath, ["scripts/verify-renderer-report.mjs", reportPath], {
      cwd: repositoryRoot,
      encoding: "utf8",
    });

    expect(result.status, `${result.stdout}${result.stderr}`).toBe(0);
    expect(result.stderr).toBe("");
    expect(result.stdout).toContain("Renderer report passed: 56 operations and 56 tabs");
  });
});
