#!/usr/bin/env bash
# Extract, verbatim, the producer structs that the contract fixtures serialise.
#
# Only the types reachable from the two emitted fixtures are extracted. Pulling
# in more (the campaign payloads, say) would make the manifest's
# producerTreeClean flag depend on files that are never serialised.
#
# The manifest's `serverCommit` and `producerTreeClean` attestations describe
# the tree this script read. They used to be typed into the manifest by hand
# with nothing deriving or checking them; now the script derives both, refuses
# a dirty source outright, and stamps the commit into the generated header so
# the next capture cannot attest to a revision nobody verified. The manifest
# itself is still edited by hand — copy the printed values.
set -euo pipefail

server="${1:?usage: extract-producer-structs.sh <path-to-ahasend-server-repo>}"
out="$(cd "$(dirname "$0")" && pwd)/producer-structs.go"

# The single list both the guard and the extraction below iterate — a second
# hand-maintained copy is exactly the drift the guard exists to rule out.
extracted_files=(
  cmd/job-runner/jobs/routes/message_routing.go
  cmd/job-runner/jobs/webhooks/message.go
)

server_commit="$(git -C "$server" rev-parse HEAD)"
for f in "${extracted_files[@]}"; do
  # `diff --quiet HEAD` reports nothing for a path HEAD does not know, so an
  # untracked working-tree file would otherwise extract "clean" while
  # matching no serverCommit at all.
  if ! git -C "$server" cat-file -e "HEAD:$f" 2>/dev/null; then
    echo "refusing to extract: $f is not tracked at HEAD in $server" >&2
    exit 1
  fi
done
if ! git -C "$server" diff --quiet HEAD -- "${extracted_files[@]}"; then
  echo "refusing to extract: uncommitted changes in ${extracted_files[*]} at $server" >&2
  echo "commit them first — an extraction from a dirty tree matches no serverCommit" >&2
  exit 1
fi

{
  echo "// Code generated by extract-producer-structs.sh. DO NOT EDIT."
  echo "//"
  echo "// Verbatim struct blocks from the AhaSend server. They are compiled"
  echo "// against encoding/json so the fixture bodies carry Go's real"
  echo "// serialization semantics rather than a transcription of them."
  echo "//"
  echo "// Extracted from server commit $server_commit (extracted files clean)."
  echo "package main"
  echo
  echo 'import ('
  echo '	"time"'
  echo
  echo '	"github.com/google/uuid"'
  echo ')'
  echo
  for f in "${extracted_files[@]}"; do
    echo "// --- $f ---"
    awk '/^type .*(Payload|Data|MessageAttachmentsPayload) struct \{/,/^\}/' \
      "$server/$f"
    echo
  done
} > "$out"

echo "wrote $out"
echo "manifest attestations for this extraction:"
echo "  serverCommit:      $server_commit"
echo "  producerTreeClean: true"
