#!/usr/bin/env bash
# Extract, verbatim, the producer structs that the contract fixtures serialise.
#
# Only the types reachable from the two emitted fixtures are extracted. Pulling
# in more (the campaign payloads, say) would make the manifest's
# producerTreeClean flag depend on files that are never serialised.
set -euo pipefail

server="${1:?usage: extract-producer-structs.sh <path-to-ahasend-server-repo>}"
out="$(cd "$(dirname "$0")" && pwd)/producer-structs.go"

{
  echo "// Code generated by extract-producer-structs.sh. DO NOT EDIT."
  echo "//"
  echo "// Verbatim struct blocks from the AhaSend server. They are compiled"
  echo "// against encoding/json so the fixture bodies carry Go's real"
  echo "// serialization semantics rather than a transcription of them."
  echo "package main"
  echo
  echo 'import ('
  echo '	"time"'
  echo
  echo '	"github.com/google/uuid"'
  echo ')'
  echo
  for f in routes/message_routing webhooks/message; do
    echo "// --- cmd/job-runner/jobs/$f.go ---"
    awk '/^type .*(Payload|Data|MessageAttachmentsPayload) struct \{/,/^\}/' \
      "$server/cmd/job-runner/jobs/$f.go"
    echo
  done
} > "$out"

echo "wrote $out"
