// Code generated by extract-producer-structs.sh. DO NOT EDIT.
//
// Verbatim struct blocks from the AhaSend server. They are compiled
// against encoding/json so the fixture bodies carry Go's real
// serialization semantics rather than a transcription of them.
//
// Extracted from server commit 67ab72634ad775e5bd5d6a2962836acea27f354d (extracted files clean).
package main

import (
	"time"

	"github.com/google/uuid"
)

// --- cmd/job-runner/jobs/routes/message_routing.go ---
type MessagePayload struct {
	Type      string      `json:"type"`
	Timestamp time.Time   `json:"timestamp"`
	RouteID   uuid.UUID   `json:"route_id"`
	Data      MessageData `json:"data"`
}
type MessageData struct {
	ID                 string                      `json:"id"`
	From               string                      `json:"from"`
	ReplyTo            string                      `json:"reply_to"`
	To                 string                      `json:"to"`
	Subject            string                      `json:"subject"`
	MessageID          string                      `json:"message_id"`
	Size               int                         `json:"size"`
	SpamScore          float64                     `json:"spam_score"`
	Bounce             bool                        `json:"bounce"`
	CC                 string                      `json:"cc"`
	Date               string                      `json:"date"`
	InReplyTo          string                      `json:"in_reply_to"`
	References         string                      `json:"references"`
	AutoSubmitted      string                      `json:"auto_submitted"`
	HTMLBody           string                      `json:"html_body"`
	PlainBody          string                      `json:"plain_body"`
	ReplyFromPlainBody string                      `json:"reply_from_plain_body"`
	Attachments        []MessageAttachmentsPayload `json:"attachments"`
	Headers            map[string]string           `json:"headers,omitempty"`
}
type MessageAttachmentsPayload struct {
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	ContentID   string `json:"content_id"`
	Disposition string `json:"disposition"`
	Data        string `json:"data"`
}

// --- cmd/job-runner/jobs/webhooks/message.go ---
type MessageWebhookPayload struct {
	Type      string             `json:"type"`
	Timestamp time.Time          `json:"timestamp"`
	WebhookID uuid.UUID          `json:"webhook_id"`
	Data      MessageWebhookData `json:"data"`
}
type MessageWebhookData struct {
	AccountID       uuid.UUID        `json:"account_id"`
	Event           string           `json:"event"`
	From            string           `json:"from"`
	Recipient       string           `json:"recipient"`
	Subject         string           `json:"subject"`
	MessageID       string           `json:"message_id_header"`
	UserAgent       string           `json:"user_agent,omitempty"`
	IP              string           `json:"ip,omitempty"`
	IsBot           bool             `json:"is_bot"`
	ID              string           `json:"id"`
	DeliveryAttempt *DeliveryAttempt `json:"delivery_attempt,omitempty"`
}
type DeliveryAttempt struct {
	Classification     string `json:"classification,omitempty"`
	SMTPCode           int    `json:"smtp_code"`
	EnhancedStatusCode string `json:"enhanced_status_code,omitempty"`
	Response           string `json:"response,omitempty"`
	Description        string `json:"description,omitempty"`
	Command            string `json:"command,omitempty"`
}

// --- cmd/job-runner/jobs/webhooks/campaign_message.go ---
type CampaignMessageWebhookPayload struct {
	Type      string                     `json:"type"`
	Timestamp time.Time                  `json:"timestamp"`
	WebhookID uuid.UUID                  `json:"webhook_id"`
	Data      CampaignMessageWebhookData `json:"data"`
}
type CampaignMessageWebhookData struct {
	AccountID       uuid.UUID        `json:"account_id"`
	Event           string           `json:"event"`
	From            string           `json:"from"`
	Recipient       string           `json:"recipient"`
	Subject         string           `json:"subject"`
	MessageID       string           `json:"message_id_header"`
	UserAgent       string           `json:"user_agent,omitempty"`
	IP              string           `json:"ip,omitempty"`
	IsBot           bool             `json:"is_bot"`
	ID              string           `json:"id"`
	DeliveryAttempt *DeliveryAttempt `json:"delivery_attempt,omitempty"`
}

