#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { format, resolveConfig } from "prettier";
import { collectOperations, parseOpenApi } from "./generate-contracts.mjs";
import { digestJsonArtifact, digestYamlArtifact } from "./digest-artifact.mjs";

const EXPECTED_OPERATION_COUNT = 56;
const EXPECTED_SCHEMA_COUNT = 68;
const EXPECTED_ITERATOR_COUNT = 9;
const IDEMPOTENCY_PARAMETER = "#/components/parameters/IdempotencyKey";
const JSON_CONTENT_TYPE = "application/json";
const GENERATED_HEADER = "// Generated by scripts/generate-sdk.mjs. Do not edit.\n\n";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "..");

const outputPaths = Object.freeze({
  restTypes: "src/generated/rest-types.ts",
  operations: "src/generated/operations.ts",
  profileJson: "src/generated/operation-profile.json",
  profileDigest: "src/generated/operation-profile.sha256",
  profileTypes: "src/generated/operation-profile.ts",
  contractDigests: "src/generated/contract-digests.ts",
});

/**
 * Facade names are intentionally independent of the current resource classes.
 * This profile is the checked bridge used while later tasks migrate those
 * classes to generated operation descriptors.
 */
export const PRIMARY_OPERATION_MAPPINGS = Object.freeze([
  ["ping", "client", "ping"],
  ["getAPIKeys", "apiKeys", "list"],
  ["createAPIKey", "apiKeys", "create"],
  ["getAPIKey", "apiKeys", "get"],
  ["updateAPIKey", "apiKeys", "update"],
  ["deleteAPIKey", "apiKeys", "delete"],
  ["getDomains", "domains", "list"],
  ["createDomain", "domains", "create"],
  ["getDomain", "domains", "get"],
  ["updateDomain", "domains", "update"],
  ["deleteDomain", "domains", "delete"],
  ["checkDomainDNS", "domains", "checkDns"],
  ["getMessages", "messages", "list"],
  ["createMessage", "messages", "send"],
  ["createConversationMessage", "messages", "sendConversation"],
  ["getMessage", "messages", "get"],
  ["cancelMessage", "messages", "cancel"],
  ["getAccount", "accounts", "get"],
  ["updateAccount", "accounts", "update"],
  ["getAccountMembers", "accounts", "listMembers"],
  ["addAccountMember", "accounts", "addMember"],
  ["removeAccountMember", "accounts", "removeMember"],
  ["listSubAccounts", "subAccounts", "list"],
  ["createSubAccount", "subAccounts", "create"],
  ["getSubAccountsUsage", "subAccounts", "usage"],
  ["getSubAccount", "subAccounts", "get"],
  ["updateSubAccount", "subAccounts", "update"],
  ["deleteSubAccount", "subAccounts", "delete"],
  ["suspendSubAccount", "subAccounts", "suspend"],
  ["unsuspendSubAccount", "subAccounts", "unsuspend"],
  ["listSubAccountAPIKeys", "subAccounts", "listApiKeys"],
  ["createSubAccountAPIKey", "subAccounts", "createApiKey"],
  ["getSubAccountAPIKey", "subAccounts", "getApiKey"],
  ["updateSubAccountAPIKey", "subAccounts", "updateApiKey"],
  ["deleteSubAccountAPIKey", "subAccounts", "deleteApiKey"],
  ["getSuppressions", "suppressions", "list"],
  ["createSuppression", "suppressions", "create"],
  ["deleteSuppression", "suppressions", "delete"],
  ["deleteAllSuppressions", "suppressions", "wipe"],
  ["getRoutes", "routes", "list"],
  ["createRoute", "routes", "create"],
  ["getRoute", "routes", "get"],
  ["updateRoute", "routes", "update"],
  ["deleteRoute", "routes", "delete"],
  ["getWebhooks", "webhooks", "list"],
  ["createWebhook", "webhooks", "create"],
  ["getWebhook", "webhooks", "get"],
  ["updateWebhook", "webhooks", "update"],
  ["deleteWebhook", "webhooks", "delete"],
  ["getSMTPCredentials", "smtpCredentials", "list"],
  ["createSMTPCredential", "smtpCredentials", "create"],
  ["getSMTPCredential", "smtpCredentials", "get"],
  ["deleteSMTPCredential", "smtpCredentials", "delete"],
  ["getDeliverabilityStatistics", "statistics", "deliverability"],
  ["getBounceStatistics", "statistics", "bounces"],
  ["getDeliveryTimeStatistics", "statistics", "deliveryTimes"],
]);

export const ITERATOR_MAPPINGS = Object.freeze([
  ["getAPIKeys", "apiKeys", "iterate"],
  ["getDomains", "domains", "iterate"],
  ["getMessages", "messages", "iterate"],
  ["listSubAccounts", "subAccounts", "iterate"],
  ["listSubAccountAPIKeys", "subAccounts", "iterateApiKeys"],
  ["getSuppressions", "suppressions", "iterate"],
  ["getRoutes", "routes", "iterate"],
  ["getWebhooks", "webhooks", "iterate"],
  ["getSMTPCredentials", "smtpCredentials", "iterate"],
]);

/**
 * Resource-aware checks that cannot be expressed by a security-requirement
 * string alone. The field names are checked against the matching OpenAPI
 * operation during generation.
 */
export const AUTHORIZATION_REGISTRY = Object.freeze({
  createMessage: { kind: "body_domain", bodyPath: "from.email" },
  createConversationMessage: { kind: "body_domain", bodyPath: "from.email" },
  createRoute: { kind: "body_domain", bodyPath: "recipient" },
  getRoutes: { kind: "query_domain_required_for_scoped", queryParameter: "domain" },
  updateRoute: {
    kind: "existing_and_replacement_domain",
    resource: "route",
    resourceIdParameter: "route_id",
    existingPath: "recipient",
    replacementBodyPath: "recipient",
  },
  createWebhook: {
    kind: "all_body_domains",
    bodyPath: "domains",
    scopeBodyPath: "scope",
    globalValue: "global",
  },
  createSMTPCredential: {
    kind: "all_body_domains",
    bodyPath: "domains",
    scopeBodyPath: "scope",
    globalValue: "global",
  },
  updateWebhook: {
    kind: "existing_and_new_domains",
    resource: "webhook",
    resourceIdParameter: "webhook_id",
    existingPath: "domains",
    newBodyPath: "domains",
    scopeBodyPath: "scope",
    globalValue: "global",
  },
  getDeliverabilityStatistics: {
    kind: "comma_separated_query_domains",
    queryParameter: "sender_domain",
  },
  getBounceStatistics: {
    kind: "comma_separated_query_domains",
    queryParameter: "sender_domain",
  },
  getDeliveryTimeStatistics: {
    kind: "comma_separated_query_domains",
    queryParameter: "sender_domain",
  },
  getMessages: {
    kind: "authorized_domain_filter",
    resource: "message",
    resourceDomainPath: "sender",
  },
  getWebhooks: {
    kind: "authorized_domain_filter",
    resource: "webhook",
    resourceDomainPath: "domains",
  },
  getSMTPCredentials: {
    kind: "authorized_domain_filter",
    resource: "smtp_credential",
    resourceDomainPath: "domains",
  },
  getMessage: {
    kind: "existing_resource_domains",
    resource: "message",
    resourceIdParameter: "message_id",
    resourceDomainPath: "sender",
  },
  cancelMessage: {
    kind: "existing_resource_domains",
    resource: "message",
    resourceIdParameter: "message_id",
    resourceDomainPath: "sender",
  },
  getRoute: {
    kind: "existing_resource_domains",
    resource: "route",
    resourceIdParameter: "route_id",
    resourceDomainPath: "recipient",
  },
  deleteRoute: {
    kind: "existing_resource_domains",
    resource: "route",
    resourceIdParameter: "route_id",
    resourceDomainPath: "recipient",
  },
  getWebhook: {
    kind: "existing_resource_domains",
    resource: "webhook",
    resourceIdParameter: "webhook_id",
    resourceDomainPath: "domains",
  },
  deleteWebhook: {
    kind: "existing_resource_domains",
    resource: "webhook",
    resourceIdParameter: "webhook_id",
    resourceDomainPath: "domains",
  },
  getSMTPCredential: {
    kind: "existing_resource_domains",
    resource: "smtp_credential",
    resourceIdParameter: "smtp_credential_id",
    resourceDomainPath: "domains",
  },
  deleteSMTPCredential: {
    kind: "existing_resource_domains",
    resource: "smtp_credential",
    resourceIdParameter: "smtp_credential_id",
    resourceDomainPath: "domains",
  },
});

function assertRecord(value, location) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${location} must be a mapping`);
  }
  return value;
}

function schemaNameFromReference(reference) {
  const prefix = "#/components/schemas/";
  return typeof reference === "string" && reference.startsWith(prefix)
    ? reference.slice(prefix.length)
    : undefined;
}

function operationParameters(pathItem, operation) {
  return [
    ...(Array.isArray(pathItem.parameters) ? pathItem.parameters : []),
    ...(Array.isArray(operation.parameters) ? operation.parameters : []),
  ];
}

function dereferenceParameter(document, value) {
  const parameter = assertRecord(value, "operation parameter");
  if (parameter.$ref === undefined) return parameter;
  if (parameter.$ref === IDEMPOTENCY_PARAMETER) {
    return assertRecord(
      assertRecord(assertRecord(document.components, "components").parameters, "parameters")
        .IdempotencyKey,
      "IdempotencyKey",
    );
  }
  throw new TypeError(`Unsupported parameter reference ${JSON.stringify(parameter.$ref)}`);
}

function schemaAtBodyPath(document, operation, path) {
  const body = assertRecord(operation.requestBody, "requestBody");
  const content = assertRecord(body.content, "requestBody.content");
  let schema = assertRecord(
    assertRecord(content[JSON_CONTENT_TYPE], JSON_CONTENT_TYPE).schema,
    "body schema",
  );
  if (schema.$ref !== undefined) {
    const name = schemaNameFromReference(schema.$ref);
    if (name === undefined) throw new TypeError(`Unsupported body reference ${schema.$ref}`);
    schema = assertRecord(
      assertRecord(assertRecord(document.components, "components").schemas, "schemas")[name],
      name,
    );
  }
  for (const segment of path.split(".")) {
    const properties = assertRecord(schema.properties, `properties containing ${path}`);
    schema = assertRecord(properties[segment], `body field ${path}`);
    if (schema.$ref !== undefined) {
      const name = schemaNameFromReference(schema.$ref);
      if (name === undefined)
        throw new TypeError(`Unsupported body field reference ${schema.$ref}`);
      schema = assertRecord(
        assertRecord(assertRecord(document.components, "components").schemas, "schemas")[name],
        name,
      );
    }
  }
  return schema;
}

export function validateOperationProfile(document, profile) {
  const operations = collectOperations(document);
  const operationIds = operations.map(({ operationId }) => operationId);
  const expected = new Set(operationIds);
  const mappings = assertRecord(profile, "operation profile").operations;
  const iterators = profile.iterators;
  if (!Array.isArray(mappings) || !Array.isArray(iterators)) {
    throw new TypeError("Operation profile mappings must be arrays");
  }
  if (mappings.length !== EXPECTED_OPERATION_COUNT) {
    throw new TypeError(
      `Operation profile must contain ${EXPECTED_OPERATION_COUNT} primary mappings`,
    );
  }
  if (iterators.length !== EXPECTED_ITERATOR_COUNT) {
    throw new TypeError(
      `Operation profile must contain ${EXPECTED_ITERATOR_COUNT} iterator mappings`,
    );
  }

  const mappedIds = mappings.map((value) => assertRecord(value, "profile operation").operationId);
  const duplicateIds = mappedIds.filter((value, index) => mappedIds.indexOf(value) !== index);
  const missing = operationIds.filter((operationId) => !mappedIds.includes(operationId));
  const extra = mappedIds.filter(
    (operationId) => typeof operationId !== "string" || !expected.has(operationId),
  );
  if (duplicateIds.length > 0 || missing.length > 0 || extra.length > 0) {
    throw new TypeError(
      `Operation profile parity failure: duplicates=${JSON.stringify([...new Set(duplicateIds)])}, missing=${JSON.stringify(missing)}, extra=${JSON.stringify(extra)}`,
    );
  }

  const aliases = [...mappings, ...iterators].map((value) => {
    const mapping = assertRecord(value, "profile mapping");
    if (typeof mapping.facade !== "string" || typeof mapping.method !== "string") {
      throw new TypeError("Every profile mapping must name a facade and method");
    }
    return `${mapping.facade}.${mapping.method}`;
  });
  const duplicateAliases = aliases.filter((value, index) => aliases.indexOf(value) !== index);
  if (duplicateAliases.length > 0) {
    throw new TypeError(`Duplicate facade mappings: ${[...new Set(duplicateAliases)].join(", ")}`);
  }

  for (const value of iterators) {
    const mapping = assertRecord(value, "iterator mapping");
    if (typeof mapping.operationId !== "string" || !expected.has(mapping.operationId)) {
      throw new TypeError(
        `Iterator references unknown operation ${JSON.stringify(mapping.operationId)}`,
      );
    }
  }
  if (Object.hasOwn(profile, "digest") || Object.hasOwn(profile, "sha256")) {
    throw new TypeError("Operation profile must not contain a self-digest");
  }
}

export function validateAuthorizationRegistry(document, registry = AUTHORIZATION_REGISTRY) {
  const operations = new Map(
    collectOperations(document).map((entry) => [entry.operationId, entry]),
  );
  const allowedKinds = new Set([
    "body_domain",
    "query_domain_required_for_scoped",
    "existing_and_replacement_domain",
    "all_body_domains",
    "existing_and_new_domains",
    "comma_separated_query_domains",
    "authorized_domain_filter",
    "existing_resource_domains",
  ]);

  for (const [operationId, value] of Object.entries(registry)) {
    const entry = operations.get(operationId);
    if (entry === undefined) throw new TypeError(`Authorization rule references ${operationId}`);
    const rule = assertRecord(value, `authorization rule ${operationId}`);
    if (!allowedKinds.has(rule.kind)) {
      throw new TypeError(
        `${operationId} has unknown authorization rule ${JSON.stringify(rule.kind)}`,
      );
    }
    const pathItem = assertRecord(assertRecord(document.paths, "paths")[entry.path], entry.path);
    const parameterNames = new Map(
      operationParameters(pathItem, entry.operation)
        .map((parameter) => dereferenceParameter(document, parameter))
        .filter((parameter) => typeof parameter.name === "string")
        .map((parameter) => [parameter.name, parameter.in]),
    );

    if (
      typeof rule.queryParameter === "string" &&
      parameterNames.get(rule.queryParameter) !== "query"
    ) {
      throw new TypeError(`${operationId} has no ${rule.queryParameter} query parameter`);
    }
    if (
      typeof rule.resourceIdParameter === "string" &&
      parameterNames.get(rule.resourceIdParameter) !== "path"
    ) {
      throw new TypeError(`${operationId} has no ${rule.resourceIdParameter} path parameter`);
    }
    for (const key of ["bodyPath", "replacementBodyPath", "newBodyPath", "scopeBodyPath"]) {
      if (typeof rule[key] === "string") schemaAtBodyPath(document, entry.operation, rule[key]);
    }
    if (!Array.isArray(entry.operation.security) || entry.operation.security.length < 2) {
      throw new TypeError(`${operationId} resource authorization requires security alternatives`);
    }
  }
  return registry;
}

function createProfile(document) {
  const profile = {
    version: 1,
    operations: PRIMARY_OPERATION_MAPPINGS.map(([operationId, facade, method]) => ({
      operationId,
      facade,
      method,
    })),
    iterators: ITERATOR_MAPPINGS.map(([operationId, facade, method]) => ({
      operationId,
      facade,
      method,
    })),
  };
  validateOperationProfile(document, profile);
  return profile;
}

function propertyName(name) {
  return /^[$A-Z_a-z][$\w]*$/.test(name) ? name : JSON.stringify(name);
}

function referenceType(reference) {
  const name = schemaNameFromReference(reference);
  return name === undefined ? "unknown" : `components[\"schemas\"][${JSON.stringify(name)}]`;
}

function schemaType(schemaValue, level = 0) {
  if (schemaValue === undefined) return "unknown";
  const schema = assertRecord(schemaValue, "schema");
  if (typeof schema.$ref === "string") return referenceType(schema.$ref);
  if (Array.isArray(schema.enum))
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.const !== undefined) return JSON.stringify(schema.const);

  const combinations = [
    ["allOf", " & "],
    ["anyOf", " | "],
    ["oneOf", " | "],
  ];
  for (const [key, separator] of combinations) {
    if (Array.isArray(schema[key])) {
      const combined = schema[key]
        .map((part) => `(${schemaType(part, level + 1)})`)
        .join(separator);
      if (
        schema.type === "object" ||
        schema.properties !== undefined ||
        schema.additionalProperties !== undefined
      ) {
        const base = { ...schema };
        delete base[key];
        return `(${schemaType(base, level)}) & (${combined})`;
      }
      return combined;
    }
  }

  if (Array.isArray(schema.type)) {
    return schema.type
      .map((type) => schemaType({ ...schema, type, enum: undefined }, level))
      .filter((value, index, values) => values.indexOf(value) === index)
      .join(" | ");
  }
  if (schema.type === "null") return "null";
  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "array") return `Array<${schemaType(schema.items, level + 1)}>`;

  if (
    schema.type === "object" ||
    schema.properties !== undefined ||
    schema.additionalProperties !== undefined
  ) {
    const properties =
      schema.properties === undefined ? {} : assertRecord(schema.properties, "properties");
    const required = new Set(Array.isArray(schema.required) ? schema.required : []);
    const indent = "  ".repeat(level + 1);
    const closingIndent = "  ".repeat(level);
    const fields = Object.entries(properties).map(
      ([name, value]) =>
        `${indent}${propertyName(name)}${required.has(name) ? "" : "?"}: ${schemaType(value, level + 1)};`,
    );
    if (schema.additionalProperties === true) fields.push(`${indent}[key: string]: unknown;`);
    else if (schema.additionalProperties !== undefined && schema.additionalProperties !== false) {
      fields.push(`${indent}[key: string]: ${schemaType(schema.additionalProperties, level + 1)};`);
    }
    return fields.length === 0
      ? "Record<string, never>"
      : `{\n${fields.join("\n")}\n${closingIndent}}`;
  }
  return "unknown";
}

function operationType(document, entry) {
  const pathItem = assertRecord(assertRecord(document.paths, "paths")[entry.path], entry.path);
  const parameters = operationParameters(pathItem, entry.operation)
    .map((parameter) => dereferenceParameter(document, parameter))
    .filter((parameter) => parameter.name !== "Idempotency-Key");
  const byLocation = new Map();
  for (const parameter of parameters) {
    if (typeof parameter.in !== "string" || typeof parameter.name !== "string") continue;
    const list = byLocation.get(parameter.in) ?? [];
    list.push(parameter);
    byLocation.set(parameter.in, list);
  }
  const parameterFields = [];
  for (const location of ["path", "query", "header"]) {
    const values = byLocation.get(location);
    if (values === undefined || values.length === 0) continue;
    const fields = values.map(
      (parameter) =>
        `        ${propertyName(parameter.name)}${parameter.required === true ? "" : "?"}: ${schemaType(parameter.schema, 4)};`,
    );
    parameterFields.push(`      ${location}: {\n${fields.join("\n")}\n      };`);
  }

  const lines = ["  {", "    parameters: {"];
  lines.push(
    ...(parameterFields.length > 0 ? parameterFields : ["      path?: Record<string, never>;"]),
  );
  lines.push("    };");
  if (entry.operation.requestBody !== undefined) {
    const requestBody = assertRecord(
      entry.operation.requestBody,
      `${entry.operationId}.requestBody`,
    );
    const content = assertRecord(requestBody.content, `${entry.operationId}.requestBody.content`);
    const media = assertRecord(content[JSON_CONTENT_TYPE], `${entry.operationId} JSON body`);
    lines.push(
      `    requestBody${requestBody.required === true ? "" : "?"}: { content: { \"application/json\": ${schemaType(media.schema, 3)} } };`,
    );
  }
  lines.push("    responses: {");
  for (const [status, responseValue] of Object.entries(
    assertRecord(entry.operation.responses, "responses"),
  )) {
    const response = assertRecord(responseValue, `${entry.operationId} response ${status}`);
    const content = response.content;
    if (content === undefined) lines.push(`      ${propertyName(status)}: { content?: never };`);
    else {
      const media = assertRecord(
        assertRecord(content, "response content")[JSON_CONTENT_TYPE],
        "response JSON",
      );
      lines.push(
        `      ${propertyName(status)}: { content: { \"application/json\": ${schemaType(media.schema, 4)} } };`,
      );
    }
  }
  lines.push("    };", "  }");
  return lines.join("\n");
}

function generateRestTypes(document, operations) {
  const schemas = assertRecord(assertRecord(document.components, "components").schemas, "schemas");
  const lines = [GENERATED_HEADER.trimEnd(), "export interface paths {"];
  const paths = new Map();
  for (const entry of operations) {
    const pathOperations = paths.get(entry.path) ?? [];
    pathOperations.push(entry);
    paths.set(entry.path, pathOperations);
  }
  for (const [path, entries] of paths) {
    const methods = entries
      .map((entry) => `${entry.method}: operations[${JSON.stringify(entry.operationId)}]`)
      .join("; ");
    lines.push(`  ${JSON.stringify(path)}: { ${methods} };`);
  }
  lines.push("}", "", "export interface components {", "  schemas: {");
  for (const [name, schema] of Object.entries(schemas)) {
    lines.push(`    ${propertyName(name)}: ${schemaType(schema, 2)};`);
  }
  lines.push("  };", "}", "", "export interface operations {");
  for (const entry of operations) {
    lines.push(`  ${propertyName(entry.operationId)}: ${operationType(document, entry)};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function securityAlternatives(operation, document) {
  const security = Array.isArray(operation.security) ? operation.security : document.security;
  if (!Array.isArray(security)) return [];
  return security.map((requirementValue) => {
    const requirement = assertRecord(requirementValue, "security requirement");
    const roles = requirement.BearerAuth;
    if (!Array.isArray(roles) || !roles.every((role) => typeof role === "string")) {
      throw new TypeError("BearerAuth security requirements must contain string roles");
    }
    return roles;
  });
}

function bodyFact(operation) {
  if (operation.requestBody === undefined) return null;
  const body = assertRecord(operation.requestBody, "requestBody");
  const media = assertRecord(
    assertRecord(body.content, "requestBody.content")[JSON_CONTENT_TYPE],
    "JSON body",
  );
  const schema = assertRecord(media.schema, "request body schema");
  return {
    required: body.required === true,
    schema: schemaNameFromReference(schema.$ref) ?? "inline",
  };
}

function successFacts(operation) {
  const facts = [];
  for (const [status, responseValue] of Object.entries(
    assertRecord(operation.responses, "responses"),
  )) {
    if (!/^2\d\d$/.test(status)) continue;
    const response = assertRecord(responseValue, `response ${status}`);
    const content = response.content;
    let schema = null;
    if (content !== undefined) {
      const media = assertRecord(
        assertRecord(content, "response content")[JSON_CONTENT_TYPE],
        "response JSON",
      );
      const responseSchema = assertRecord(media.schema, "response schema");
      schema = schemaNameFromReference(responseSchema.$ref) ?? "inline";
    }
    facts.push({ status: Number(status), schema });
  }
  if (facts.length === 0) throw new TypeError("Operation has no 2xx response");
  return facts;
}

function retryMode(method, idempotency) {
  if (method === "get") return "safe";
  if (method === "put" || method === "delete") return "idempotent";
  if (idempotency) return "idempotency_key";
  return "never";
}

function generateOperations(document, operations) {
  validateAuthorizationRegistry(document);
  const descriptors = {};
  for (const entry of operations) {
    const pathItem = assertRecord(assertRecord(document.paths, "paths")[entry.path], entry.path);
    const parameters = operationParameters(pathItem, entry.operation).map((parameter) =>
      dereferenceParameter(document, parameter),
    );
    const query = parameters
      .filter((parameter) => parameter.in === "query")
      .map((parameter) => ({ name: parameter.name, required: parameter.required === true }));
    const idempotency = parameters.some((parameter) => parameter.name === "Idempotency-Key");
    descriptors[entry.operationId] = {
      method: entry.method.toUpperCase(),
      path: entry.path,
      query,
      body: bodyFact(entry.operation),
      success: successFacts(entry.operation),
      idempotency,
      retry: retryMode(entry.method, idempotency),
      security: securityAlternatives(entry.operation, document),
      resourceAuthorization: AUTHORIZATION_REGISTRY[entry.operationId] ?? null,
    };
  }

  return `${GENERATED_HEADER}export type RetryMode = "safe" | "idempotent" | "idempotency_key" | "never";

export type ResourceAuthorizationRule =
  | { readonly kind: "body_domain"; readonly bodyPath: "from.email" | "recipient" }
  | { readonly kind: "query_domain_required_for_scoped"; readonly queryParameter: "domain" }
  | {
      readonly kind: "existing_and_replacement_domain";
      readonly resource: "route";
      readonly resourceIdParameter: "route_id";
      readonly existingPath: "recipient";
      readonly replacementBodyPath: "recipient";
    }
  | {
      readonly kind: "all_body_domains";
      readonly bodyPath: "domains";
      readonly scopeBodyPath: "scope";
      readonly globalValue: "global";
    }
  | {
      readonly kind: "existing_and_new_domains";
      readonly resource: "webhook";
      readonly resourceIdParameter: "webhook_id";
      readonly existingPath: "domains";
      readonly newBodyPath: "domains";
      readonly scopeBodyPath: "scope";
      readonly globalValue: "global";
    }
  | { readonly kind: "comma_separated_query_domains"; readonly queryParameter: "sender_domain" }
  | {
      readonly kind: "authorized_domain_filter";
      readonly resource: "message" | "webhook" | "smtp_credential";
      readonly resourceDomainPath: "sender" | "domains";
    }
  | {
      readonly kind: "existing_resource_domains";
      readonly resource: "message" | "route" | "webhook" | "smtp_credential";
      readonly resourceIdParameter:
        | "message_id"
        | "route_id"
        | "webhook_id"
        | "smtp_credential_id";
      readonly resourceDomainPath: "sender" | "recipient" | "domains";
    };

export interface OperationDescriptor {
  readonly method: "GET" | "POST" | "PUT" | "DELETE";
  readonly path: string;
  readonly query: readonly { readonly name: string; readonly required: boolean }[];
  readonly body: { readonly required: boolean; readonly schema: string } | null;
  readonly success: readonly { readonly status: number; readonly schema: string | null }[];
  readonly idempotency: boolean;
  readonly retry: RetryMode;
  readonly security: readonly (readonly string[])[];
  readonly resourceAuthorization: ResourceAuthorizationRule | null;
}

export const RESOURCE_AUTHORIZATION = ${JSON.stringify(AUTHORIZATION_REGISTRY, null, 2)} as const satisfies Readonly<
  Partial<Record<keyof typeof OPERATION_DESCRIPTORS, ResourceAuthorizationRule>>
>;

export const OPERATION_DESCRIPTORS = ${JSON.stringify(descriptors, null, 2)} as const satisfies Readonly<
  Record<string, OperationDescriptor>
>;

export type OperationId = keyof typeof OPERATION_DESCRIPTORS;
`;
}

function generateProfileTypes() {
  return `${GENERATED_HEADER}import profileJson from "./operation-profile.json";
import type { OperationId } from "./operations.js";

export interface OperationProfileMapping {
  readonly operationId: OperationId;
  readonly facade: string;
  readonly method: string;
}

export interface OperationProfile {
  readonly version: 1;
  readonly operations: readonly OperationProfileMapping[];
  readonly iterators: readonly OperationProfileMapping[];
}

// JSON is the canonical table. This module only supplies its checked TypeScript view.
export const OPERATION_PROFILE = profileJson as unknown as OperationProfile;
`;
}

function generateContractDigests(openApiDigest, profileDigest) {
  return `${GENERATED_HEADER}export const OPENAPI_SHA256 = ${JSON.stringify(openApiDigest)} as const;
export const OPERATION_PROFILE_SHA256 = ${JSON.stringify(profileDigest)} as const;

export const CONTRACT_DIGESTS = Object.freeze({
  openapi: OPENAPI_SHA256,
  operationProfile: OPERATION_PROFILE_SHA256,
});
`;
}

export async function generateSdkArtifacts(openApiSource) {
  const document = parseOpenApi(openApiSource);
  const operations = collectOperations(document);
  const schemas = Object.keys(
    assertRecord(assertRecord(document.components, "components").schemas, "schemas"),
  );
  if (operations.length !== EXPECTED_OPERATION_COUNT || schemas.length !== EXPECTED_SCHEMA_COUNT) {
    throw new TypeError(
      `Expected ${EXPECTED_OPERATION_COUNT} operations and ${EXPECTED_SCHEMA_COUNT} schemas; received ${operations.length} and ${schemas.length}`,
    );
  }
  const profile = createProfile(document);
  const profileDigest = digestJsonArtifact(profile);
  const profileJson = `${JSON.stringify(profile, null, 2)}\n`;
  const prettierConfig = (await resolveConfig(resolve(repositoryRoot, ".prettierrc.json"))) ?? {};
  const typescriptArtifacts = await Promise.all(
    [
      [outputPaths.restTypes, generateRestTypes(document, operations)],
      [outputPaths.operations, generateOperations(document, operations)],
      [outputPaths.profileTypes, generateProfileTypes()],
      [
        outputPaths.contractDigests,
        generateContractDigests(
          digestYamlArtifact(Buffer.from(openApiSource, "utf8")),
          profileDigest,
        ),
      ],
    ].map(async ([path, source]) => [
      path,
      await format(source, { ...prettierConfig, filepath: resolve(repositoryRoot, path) }),
    ]),
  );
  return new Map([
    ...typescriptArtifacts,
    [outputPaths.profileJson, profileJson],
    [outputPaths.profileDigest, `${profileDigest}\n`],
  ]);
}

async function run(check) {
  const openApiSource = await readFile(resolve(repositoryRoot, "openapi.yaml"), "utf8");
  const artifacts = await generateSdkArtifacts(openApiSource);
  const drift = [];
  for (const [path, expected] of artifacts) {
    const absolutePath = resolve(repositoryRoot, path);
    if (check) {
      let actual;
      try {
        actual = await readFile(absolutePath, "utf8");
      } catch (error) {
        if (error !== null && typeof error === "object" && error.code === "ENOENT")
          actual = undefined;
        else throw error;
      }
      if (actual !== expected) drift.push(path);
    } else {
      await mkdir(dirname(absolutePath), { recursive: true });
      await writeFile(absolutePath, expected, "utf8");
    }
  }
  if (drift.length > 0) {
    throw new TypeError(`Generated SDK artifacts are stale: ${drift.join(", ")}`);
  }
}

async function main() {
  const arguments_ = process.argv.slice(2);
  if (arguments_.some((argument) => argument !== "--check") || arguments_.length > 1) {
    throw new TypeError("Usage: node scripts/generate-sdk.mjs [--check]");
  }
  await run(arguments_[0] === "--check");
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  main().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`generate-sdk: ${message}\n`);
    process.exitCode = 1;
  });
}
