#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { format, resolveConfig } from "prettier";
import {
  collectOperations,
  parseOpenApi,
  parseWebhookContract,
  validateWebhookContract,
} from "./generate-contracts.mjs";
import { digestJsonArtifact, digestYamlArtifact } from "./digest-artifact.mjs";

const EXPECTED_OPERATION_COUNT = 56;
const EXPECTED_SCHEMA_COUNT = 68;
const EXPECTED_ITERATOR_COUNT = 9;
const EXPECTED_WEBHOOK_COUNT = 11;
const EXPECTED_WEBHOOK_SCHEMA_COUNT = 18;
const IDEMPOTENCY_PARAMETER = "#/components/parameters/IdempotencyKey";
const JSON_CONTENT_TYPE = "application/json";
const GENERATED_HEADER = "// Generated by scripts/generate-sdk.mjs. Do not edit.\n\n";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "..");

const outputPaths = Object.freeze({
  restTypes: "src/generated/rest-types.ts",
  operations: "src/generated/operations.ts",
  profileJson: "src/generated/operation-profile.json",
  profileDigest: "src/generated/operation-profile.sha256",
  profileTypes: "src/generated/operation-profile.ts",
  contractDigests: "src/generated/contract-digests.ts",
  webhookTypes: "src/generated/webhook-types.ts",
  webhookValidators: "src/generated/webhook-validators.ts",
});

/**
 * Facade names are intentionally independent of the current resource classes.
 * This profile is the checked bridge used while later tasks migrate those
 * classes to generated operation descriptors.
 */
export const PRIMARY_OPERATION_MAPPINGS = Object.freeze([
  ["ping", "client", "ping"],
  ["getAPIKeys", "apiKeys", "list"],
  ["createAPIKey", "apiKeys", "create"],
  ["getAPIKey", "apiKeys", "get"],
  ["updateAPIKey", "apiKeys", "update"],
  ["deleteAPIKey", "apiKeys", "delete"],
  ["getDomains", "domains", "list"],
  ["createDomain", "domains", "create"],
  ["getDomain", "domains", "get"],
  ["updateDomain", "domains", "update"],
  ["deleteDomain", "domains", "delete"],
  ["checkDomainDNS", "domains", "checkDns"],
  ["getMessages", "messages", "list"],
  ["createMessage", "messages", "send"],
  ["createConversationMessage", "messages", "sendConversation"],
  ["getMessage", "messages", "get"],
  ["cancelMessage", "messages", "cancel"],
  ["getAccount", "accounts", "get"],
  ["updateAccount", "accounts", "update"],
  ["getAccountMembers", "accounts", "listMembers"],
  ["addAccountMember", "accounts", "addMember"],
  ["removeAccountMember", "accounts", "removeMember"],
  ["listSubAccounts", "subAccounts", "list"],
  ["createSubAccount", "subAccounts", "create"],
  ["getSubAccountsUsage", "subAccounts", "usage"],
  ["getSubAccount", "subAccounts", "get"],
  ["updateSubAccount", "subAccounts", "update"],
  ["deleteSubAccount", "subAccounts", "delete"],
  ["suspendSubAccount", "subAccounts", "suspend"],
  ["unsuspendSubAccount", "subAccounts", "unsuspend"],
  ["listSubAccountAPIKeys", "subAccounts.apiKeys", "list"],
  ["createSubAccountAPIKey", "subAccounts.apiKeys", "create"],
  ["getSubAccountAPIKey", "subAccounts.apiKeys", "get"],
  ["updateSubAccountAPIKey", "subAccounts.apiKeys", "update"],
  ["deleteSubAccountAPIKey", "subAccounts.apiKeys", "delete"],
  ["getSuppressions", "suppressions", "list"],
  ["createSuppression", "suppressions", "create"],
  ["deleteSuppression", "suppressions", "delete"],
  ["deleteAllSuppressions", "suppressions", "wipe"],
  ["getRoutes", "routes", "list"],
  ["createRoute", "routes", "create"],
  ["getRoute", "routes", "get"],
  ["updateRoute", "routes", "update"],
  ["deleteRoute", "routes", "delete"],
  ["getWebhooks", "webhooks", "list"],
  ["createWebhook", "webhooks", "create"],
  ["getWebhook", "webhooks", "get"],
  ["updateWebhook", "webhooks", "update"],
  ["deleteWebhook", "webhooks", "delete"],
  ["getSMTPCredentials", "smtpCredentials", "list"],
  ["createSMTPCredential", "smtpCredentials", "create"],
  ["getSMTPCredential", "smtpCredentials", "get"],
  ["deleteSMTPCredential", "smtpCredentials", "delete"],
  ["getDeliverabilityStatistics", "statistics", "deliverability"],
  ["getBounceStatistics", "statistics", "bounces"],
  ["getDeliveryTimeStatistics", "statistics", "deliveryTimes"],
]);

export const ITERATOR_MAPPINGS = Object.freeze([
  ["getAPIKeys", "apiKeys", "iterate"],
  ["getDomains", "domains", "iterate"],
  ["getMessages", "messages", "iterate"],
  ["listSubAccounts", "subAccounts", "iterate"],
  ["listSubAccountAPIKeys", "subAccounts.apiKeys", "iterate"],
  ["getSuppressions", "suppressions", "iterate"],
  ["getRoutes", "routes", "iterate"],
  ["getWebhooks", "webhooks", "iterate"],
  ["getSMTPCredentials", "smtpCredentials", "iterate"],
]);

/**
 * Resource-aware checks that cannot be expressed by a security-requirement
 * string alone. The field names are checked against the matching OpenAPI
 * operation during generation.
 */
export const AUTHORIZATION_REGISTRY = Object.freeze({
  createMessage: {
    kind: "body_domain",
    bodyPath: "from.email",
    quantifier: "one",
    roles: { global: "messages:send:all", domain: "messages:send:{domain}" },
    summary:
      "Authorization requires `messages:send:all` or `messages:send:{domain}` matching the domain in `from.email`.",
  },
  createConversationMessage: {
    kind: "body_domain",
    bodyPath: "from.email",
    quantifier: "one",
    roles: { global: "messages:send:all", domain: "messages:send:{domain}" },
    summary:
      "Authorization requires `messages:send:all` or `messages:send:{domain}` matching the domain in `from.email`.",
  },
  createRoute: {
    kind: "body_domain",
    bodyPath: "recipient",
    quantifier: "one",
    roles: { global: "routes:write:all", domain: "routes:write:{domain}" },
    summary:
      "Authorization requires `routes:write:all` or `routes:write:{domain}` matching the domain in `recipient`.",
  },
  getRoutes: {
    kind: "query_domain_required_for_scoped",
    queryParameter: "domain",
    condition: "scoped_role_requires_filter",
    roles: { global: "routes:read:all", domain: "routes:read:{domain}" },
    summary:
      "Authorization requires `routes:read:all`, or `routes:read:{domain}` with its matching `domain` query filter.",
  },
  updateRoute: {
    kind: "existing_and_replacement_domain",
    resource: "route",
    resourceIdParameter: "route_id",
    existingPath: "recipient",
    replacementBodyPath: "recipient",
    quantifier: "every",
    roles: { global: "routes:write:all", domain: "routes:write:{domain}" },
    summary:
      "Authorization requires `routes:write:all`, or `routes:write:{domain}` for both the existing and replacement `recipient` domains.",
  },
  createWebhook: {
    kind: "all_body_domains",
    bodyPath: "domains",
    scopeBodyPath: "scope",
    globalValue: "global",
    quantifier: "every",
    condition: "global_scope_requires_global_role",
    roles: { global: "webhooks:write:all", domain: "webhooks:write:{domain}" },
    summary:
      'A `scoped` webhook requires `webhooks:write:{domain}` for every `domains` entry; `scope: "global"` requires `webhooks:write:all`.',
  },
  createSMTPCredential: {
    kind: "all_body_domains",
    bodyPath: "domains",
    scopeBodyPath: "scope",
    globalValue: "global",
    quantifier: "every",
    condition: "global_scope_requires_global_role",
    roles: {
      global: "smtp-credentials:write:all",
      domain: "smtp-credentials:write:{domain}",
    },
    summary:
      'A `scoped` SMTP credential requires `smtp-credentials:write:{domain}` for every `domains` entry; `scope: "global"` requires `smtp-credentials:write:all`.',
  },
  updateWebhook: {
    kind: "existing_and_new_domains",
    resource: "webhook",
    resourceIdParameter: "webhook_id",
    existingPath: "domains",
    newBodyPath: "domains",
    scopeBodyPath: "scope",
    globalValue: "global",
    quantifier: "every",
    transition: "global_scope_requires_global_role",
    roles: { global: "webhooks:write:all", domain: "webhooks:write:{domain}" },
    summary:
      "Authorization requires `webhooks:write:{domain}` for the existing webhook and every new `domains` entry; changing `scope` to `global` requires `webhooks:write:all`.",
  },
  getDeliverabilityStatistics: {
    kind: "comma_separated_query_domains",
    queryParameter: "sender_domain",
    quantifier: "every",
    roles: {
      global: "statistics-transactional:read:all",
      domain: "statistics-transactional:read:{domain}",
    },
    summary:
      "Authorization requires `statistics-transactional:read:all` or `statistics-transactional:read:{domain}` for every comma-separated `sender_domain` value.",
  },
  getBounceStatistics: {
    kind: "comma_separated_query_domains",
    queryParameter: "sender_domain",
    quantifier: "every",
    roles: {
      global: "statistics-transactional:read:all",
      domain: "statistics-transactional:read:{domain}",
    },
    summary:
      "Authorization requires `statistics-transactional:read:all` or `statistics-transactional:read:{domain}` for every comma-separated `sender_domain` value.",
  },
  getDeliveryTimeStatistics: {
    kind: "comma_separated_query_domains",
    queryParameter: "sender_domain",
    quantifier: "every",
    roles: {
      global: "statistics-transactional:read:all",
      domain: "statistics-transactional:read:{domain}",
    },
    summary:
      "Authorization requires `statistics-transactional:read:all` or `statistics-transactional:read:{domain}` for every comma-separated `sender_domain` value.",
  },
  getMessages: {
    kind: "authorized_domain_filter",
    resource: "message",
    resourceDomainPath: "sender",
    quantifier: "one",
    roles: { global: "messages:read:all", domain: "messages:read:{domain}" },
    summary:
      "`messages:read:all` returns every message; `messages:read:{domain}` returns only messages whose `sender` domain is authorized.",
  },
  getWebhooks: {
    kind: "authorized_domain_filter",
    resource: "webhook",
    resourceDomainPath: "domains",
    quantifier: "at_least_one",
    roles: { global: "webhooks:read:all", domain: "webhooks:read:{domain}" },
    summary:
      "`webhooks:read:all` returns every webhook; `webhooks:read:{domain}` returns only webhooks with at least one authorized `domains` entry.",
  },
  getSMTPCredentials: {
    kind: "authorized_domain_filter",
    resource: "smtp_credential",
    resourceDomainPath: "domains",
    quantifier: "at_least_one",
    roles: {
      global: "smtp-credentials:read:all",
      domain: "smtp-credentials:read:{domain}",
    },
    summary:
      "`smtp-credentials:read:all` returns every SMTP credential; `smtp-credentials:read:{domain}` returns only credentials with at least one authorized `domains` entry.",
  },
  getMessage: {
    kind: "existing_resource_domains",
    resource: "message",
    resourceIdParameter: "message_id",
    resourceDomainPath: "sender",
    quantifier: "one",
    roles: { global: "messages:read:all", domain: "messages:read:{domain}" },
    summary:
      "Authorization requires `messages:read:all` or `messages:read:{domain}` matching the message's `sender` domain.",
  },
  cancelMessage: {
    kind: "existing_resource_domains",
    resource: "message",
    resourceIdParameter: "message_id",
    resourceDomainPath: "sender",
    quantifier: "one",
    roles: { global: "messages:cancel:all", domain: "messages:cancel:{domain}" },
    summary:
      "Authorization requires `messages:cancel:all` or `messages:cancel:{domain}` matching the message's `sender` domain.",
  },
  getRoute: {
    kind: "existing_resource_domains",
    resource: "route",
    resourceIdParameter: "route_id",
    resourceDomainPath: "recipient",
    quantifier: "one",
    roles: { global: "routes:read:all", domain: "routes:read:{domain}" },
    summary:
      "Authorization requires `routes:read:all` or `routes:read:{domain}` matching the route's `recipient` domain.",
  },
  deleteRoute: {
    kind: "existing_resource_domains",
    resource: "route",
    resourceIdParameter: "route_id",
    resourceDomainPath: "recipient",
    quantifier: "one",
    roles: { global: "routes:delete:all", domain: "routes:delete:{domain}" },
    summary:
      "Authorization requires `routes:delete:all` or `routes:delete:{domain}` matching the route's `recipient` domain.",
  },
  getWebhook: {
    kind: "existing_resource_domains",
    resource: "webhook",
    resourceIdParameter: "webhook_id",
    resourceDomainPath: "domains",
    quantifier: "at_least_one",
    roles: { global: "webhooks:read:all", domain: "webhooks:read:{domain}" },
    summary:
      "Authorization requires `webhooks:read:all` or `webhooks:read:{domain}` matching at least one webhook `domains` entry.",
  },
  deleteWebhook: {
    kind: "existing_resource_domains",
    resource: "webhook",
    resourceIdParameter: "webhook_id",
    resourceDomainPath: "domains",
    quantifier: "at_least_one",
    roles: { global: "webhooks:delete:all", domain: "webhooks:delete:{domain}" },
    summary:
      "Authorization requires `webhooks:delete:all` or `webhooks:delete:{domain}` matching at least one webhook `domains` entry.",
  },
  getSMTPCredential: {
    kind: "existing_resource_domains",
    resource: "smtp_credential",
    resourceIdParameter: "smtp_credential_id",
    resourceDomainPath: "domains",
    quantifier: "at_least_one",
    roles: {
      global: "smtp-credentials:read:all",
      domain: "smtp-credentials:read:{domain}",
    },
    summary:
      "Authorization requires `smtp-credentials:read:all` or `smtp-credentials:read:{domain}` matching at least one credential `domains` entry.",
  },
  deleteSMTPCredential: {
    kind: "existing_resource_domains",
    resource: "smtp_credential",
    resourceIdParameter: "smtp_credential_id",
    resourceDomainPath: "domains",
    quantifier: "at_least_one",
    roles: {
      global: "smtp-credentials:delete:all",
      domain: "smtp-credentials:delete:{domain}",
    },
    summary:
      "Authorization requires `smtp-credentials:delete:all` or `smtp-credentials:delete:{domain}` matching at least one credential `domains` entry.",
  },
});

function assertRecord(value, location) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${location} must be a mapping`);
  }
  return value;
}

function schemaNameFromReference(reference) {
  const prefix = "#/components/schemas/";
  return typeof reference === "string" && reference.startsWith(prefix)
    ? reference.slice(prefix.length)
    : undefined;
}

function responseNameFromReference(reference) {
  const prefix = "#/components/responses/";
  return typeof reference === "string" && reference.startsWith(prefix)
    ? reference.slice(prefix.length)
    : undefined;
}

export function dereferenceResponse(document, value) {
  let response = assertRecord(value, "operation response");
  const references = new Set();
  while (response.$ref !== undefined) {
    const reference = response.$ref;
    const name = responseNameFromReference(reference);
    if (name === undefined) {
      throw new TypeError(`Unsupported response reference ${JSON.stringify(reference)}`);
    }
    if (references.has(reference)) {
      throw new TypeError(`Circular response reference ${JSON.stringify(reference)}`);
    }
    references.add(reference);
    response = assertRecord(
      assertRecord(assertRecord(document.components, "components").responses, "responses")[name],
      name,
    );
  }
  return response;
}

function operationParameters(pathItem, operation) {
  return [
    ...(Array.isArray(pathItem.parameters) ? pathItem.parameters : []),
    ...(Array.isArray(operation.parameters) ? operation.parameters : []),
  ];
}

function dereferenceParameter(document, value) {
  const parameter = assertRecord(value, "operation parameter");
  if (parameter.$ref === undefined) return parameter;
  if (parameter.$ref === IDEMPOTENCY_PARAMETER) {
    return assertRecord(
      assertRecord(assertRecord(document.components, "components").parameters, "parameters")
        .IdempotencyKey,
      "IdempotencyKey",
    );
  }
  throw new TypeError(`Unsupported parameter reference ${JSON.stringify(parameter.$ref)}`);
}

function schemaAtBodyPath(document, operation, path) {
  const body = assertRecord(operation.requestBody, "requestBody");
  const content = assertRecord(body.content, "requestBody.content");
  let schema = assertRecord(
    assertRecord(content[JSON_CONTENT_TYPE], JSON_CONTENT_TYPE).schema,
    "body schema",
  );
  if (schema.$ref !== undefined) {
    const name = schemaNameFromReference(schema.$ref);
    if (name === undefined) throw new TypeError(`Unsupported body reference ${schema.$ref}`);
    schema = assertRecord(
      assertRecord(assertRecord(document.components, "components").schemas, "schemas")[name],
      name,
    );
  }
  for (const segment of path.split(".")) {
    const properties = assertRecord(schema.properties, `properties containing ${path}`);
    schema = assertRecord(properties[segment], `body field ${path}`);
    if (schema.$ref !== undefined) {
      const name = schemaNameFromReference(schema.$ref);
      if (name === undefined)
        throw new TypeError(`Unsupported body field reference ${schema.$ref}`);
      schema = assertRecord(
        assertRecord(assertRecord(document.components, "components").schemas, "schemas")[name],
        name,
      );
    }
  }
  return schema;
}

export function validateOperationProfile(document, profile) {
  const operations = collectOperations(document);
  const operationIds = operations.map(({ operationId }) => operationId);
  const expected = new Set(operationIds);
  const mappings = assertRecord(profile, "operation profile").operations;
  const iterators = profile.iterators;
  if (!Array.isArray(mappings) || !Array.isArray(iterators)) {
    throw new TypeError("Operation profile mappings must be arrays");
  }
  if (mappings.length !== EXPECTED_OPERATION_COUNT) {
    throw new TypeError(
      `Operation profile must contain ${EXPECTED_OPERATION_COUNT} primary mappings`,
    );
  }
  if (iterators.length !== EXPECTED_ITERATOR_COUNT) {
    throw new TypeError(
      `Operation profile must contain ${EXPECTED_ITERATOR_COUNT} iterator mappings`,
    );
  }

  const mappedIds = mappings.map((value) => assertRecord(value, "profile operation").operationId);
  const duplicateIds = mappedIds.filter((value, index) => mappedIds.indexOf(value) !== index);
  const missing = operationIds.filter((operationId) => !mappedIds.includes(operationId));
  const extra = mappedIds.filter(
    (operationId) => typeof operationId !== "string" || !expected.has(operationId),
  );
  if (duplicateIds.length > 0 || missing.length > 0 || extra.length > 0) {
    throw new TypeError(
      `Operation profile parity failure: duplicates=${JSON.stringify([...new Set(duplicateIds)])}, missing=${JSON.stringify(missing)}, extra=${JSON.stringify(extra)}`,
    );
  }

  const aliases = [...mappings, ...iterators].map((value) => {
    const mapping = assertRecord(value, "profile mapping");
    if (typeof mapping.facade !== "string" || typeof mapping.method !== "string") {
      throw new TypeError("Every profile mapping must name a facade and method");
    }
    return `${mapping.facade}.${mapping.method}`;
  });
  const duplicateAliases = aliases.filter((value, index) => aliases.indexOf(value) !== index);
  if (duplicateAliases.length > 0) {
    throw new TypeError(`Duplicate facade mappings: ${[...new Set(duplicateAliases)].join(", ")}`);
  }

  for (const value of iterators) {
    const mapping = assertRecord(value, "iterator mapping");
    if (typeof mapping.operationId !== "string" || !expected.has(mapping.operationId)) {
      throw new TypeError(
        `Iterator references unknown operation ${JSON.stringify(mapping.operationId)}`,
      );
    }
  }
  if (Object.hasOwn(profile, "digest") || Object.hasOwn(profile, "sha256")) {
    throw new TypeError("Operation profile must not contain a self-digest");
  }
}

export function validateAuthorizationRegistry(document, registry = AUTHORIZATION_REGISTRY) {
  const operations = new Map(
    collectOperations(document).map((entry) => [entry.operationId, entry]),
  );
  const kindSemantics = {
    body_domain: { quantifier: "one" },
    query_domain_required_for_scoped: { condition: "scoped_role_requires_filter" },
    existing_and_replacement_domain: { quantifier: "every" },
    all_body_domains: {
      quantifier: "every",
      condition: "global_scope_requires_global_role",
    },
    existing_and_new_domains: {
      quantifier: "every",
      transition: "global_scope_requires_global_role",
    },
    comma_separated_query_domains: { quantifier: "every" },
    authorized_domain_filter: {},
    existing_resource_domains: {},
  };
  const resourceSchemas = {
    message: "MessageSummary",
    route: "Route",
    webhook: "Webhook",
    smtp_credential: "SMTPCredential",
  };

  for (const [operationId, value] of Object.entries(registry)) {
    const entry = operations.get(operationId);
    if (entry === undefined) throw new TypeError(`Authorization rule references ${operationId}`);
    const rule = assertRecord(value, `authorization rule ${operationId}`);
    const expectedSemantics = kindSemantics[rule.kind];
    if (expectedSemantics === undefined) {
      throw new TypeError(
        `${operationId} has unknown authorization rule ${JSON.stringify(rule.kind)}`,
      );
    }
    for (const [key, expected] of Object.entries(expectedSemantics)) {
      if (rule[key] !== expected) {
        throw new TypeError(
          `${operationId} authorization ${key} must be ${JSON.stringify(expected)}`,
        );
      }
    }
    if (
      !["one", "at_least_one"].includes(rule.quantifier) &&
      ["authorized_domain_filter", "existing_resource_domains"].includes(rule.kind)
    ) {
      throw new TypeError(`${operationId} authorization quantifier must describe domain matching`);
    }
    if (
      typeof rule.summary !== "string" ||
      rule.summary.length === 0 ||
      rule.summary.trim() !== rule.summary
    ) {
      throw new TypeError(`${operationId} authorization summary must be a stable non-empty string`);
    }
    const roles = assertRecord(rule.roles, `${operationId} authorization roles`);
    if (typeof roles.global !== "string" || typeof roles.domain !== "string") {
      throw new TypeError(`${operationId} authorization roles must name global and domain roles`);
    }
    const pathItem = assertRecord(assertRecord(document.paths, "paths")[entry.path], entry.path);
    const parameterNames = new Map(
      operationParameters(pathItem, entry.operation)
        .map((parameter) => dereferenceParameter(document, parameter))
        .filter((parameter) => typeof parameter.name === "string")
        .map((parameter) => [parameter.name, parameter.in]),
    );

    if (
      typeof rule.queryParameter === "string" &&
      parameterNames.get(rule.queryParameter) !== "query"
    ) {
      throw new TypeError(`${operationId} has no ${rule.queryParameter} query parameter`);
    }
    if (
      typeof rule.resourceIdParameter === "string" &&
      parameterNames.get(rule.resourceIdParameter) !== "path"
    ) {
      throw new TypeError(`${operationId} has no ${rule.resourceIdParameter} path parameter`);
    }
    for (const key of ["bodyPath", "replacementBodyPath", "newBodyPath", "scopeBodyPath"]) {
      if (typeof rule[key] === "string") schemaAtBodyPath(document, entry.operation, rule[key]);
    }
    const resourceSchemaName = resourceSchemas[rule.resource];
    for (const key of ["existingPath", "resourceDomainPath"]) {
      if (typeof rule[key] !== "string") continue;
      if (resourceSchemaName === undefined) {
        throw new TypeError(`${operationId} has unknown resource ${JSON.stringify(rule.resource)}`);
      }
      const schemas = assertRecord(
        assertRecord(document.components, "components").schemas,
        "schemas",
      );
      const resourceSchema = assertRecord(schemas[resourceSchemaName], resourceSchemaName);
      const properties = assertRecord(
        resourceSchema.properties,
        `${resourceSchemaName}.properties`,
      );
      if (properties[rule[key]] === undefined) {
        throw new TypeError(
          `${operationId} has no ${rule[key]} field on resource ${rule.resource}`,
        );
      }
    }
    if (!Array.isArray(entry.operation.security) || entry.operation.security.length !== 2) {
      throw new TypeError(
        `${operationId} resource authorization requires exactly two security alternatives`,
      );
    }
    const securityRoles = entry.operation.security.map((requirementValue) => {
      const requirement = assertRecord(requirementValue, `${operationId} security requirement`);
      const bearerRoles = requirement.BearerAuth;
      if (
        Object.keys(requirement).length !== 1 ||
        !Array.isArray(bearerRoles) ||
        bearerRoles.length !== 1 ||
        typeof bearerRoles[0] !== "string"
      ) {
        throw new TypeError(
          `${operationId} security alternatives must be singleton BearerAuth requirements`,
        );
      }
      return bearerRoles[0];
    });
    if (
      securityRoles.length !== 2 ||
      !securityRoles.includes(roles.global) ||
      !securityRoles.includes(roles.domain)
    ) {
      throw new TypeError(
        `${operationId} authorization role pair does not match its security roles`,
      );
    }
  }
  return registry;
}

function createProfile(document) {
  const profile = {
    version: 1,
    operations: PRIMARY_OPERATION_MAPPINGS.map(([operationId, facade, method]) => ({
      operationId,
      facade,
      method,
    })),
    iterators: ITERATOR_MAPPINGS.map(([operationId, facade, method]) => ({
      operationId,
      facade,
      method,
    })),
  };
  validateOperationProfile(document, profile);
  return profile;
}

function propertyName(name) {
  return /^[$A-Z_a-z][$\w]*$/.test(name) ? name : JSON.stringify(name);
}

function referenceType(reference) {
  const name = schemaNameFromReference(reference);
  return name === undefined ? "unknown" : `components[\"schemas\"][${JSON.stringify(name)}]`;
}

function conditionalType(schema, enclosingSchemaValue, level, componentSchemasValue) {
  if (enclosingSchemaValue === undefined) {
    throw new TypeError("Conditional schema requires an enclosing schema");
  }
  const enclosingSchema = assertRecord(enclosingSchemaValue, "conditional enclosing schema");
  const condition = assertRecord(schema.if, "conditional if schema");
  const thenSchema = assertRecord(schema.then, "conditional then schema");
  const conditionProperties =
    condition.properties === undefined
      ? {}
      : assertRecord(condition.properties, "conditional properties");
  const enclosingProperties = assertRecord(
    enclosingSchema.properties,
    "conditional enclosing properties",
  );
  const conditionRequired = new Set(
    Array.isArray(condition.required)
      ? condition.required.filter((name) => typeof name === "string")
      : [],
  );
  const negatedFields = [];

  for (const [name, value] of Object.entries(conditionProperties)) {
    const propertyCondition = assertRecord(value, `conditional property ${name}`);
    if (propertyCondition.const === undefined) {
      throw new TypeError(`Conditional property ${name} must use const`);
    }
    const enclosingProperty = enclosingProperties[name];
    if (enclosingProperty === undefined) {
      throw new TypeError(`Conditional property ${name} is absent from its enclosing schema`);
    }
    const indent = "  ".repeat(level + 1);
    const closingIndent = "  ".repeat(level);
    negatedFields.push(
      `\n${indent}${propertyName(name)}${conditionRequired.has(name) ? "?" : ""}: Exclude<${schemaType(enclosingProperty, level + 1, undefined, componentSchemasValue)}, ${JSON.stringify(propertyCondition.const)}>;\n${closingIndent}`,
    );
  }

  for (const name of conditionRequired) {
    if (!Object.hasOwn(conditionProperties, name)) {
      const indent = "  ".repeat(level + 1);
      const closingIndent = "  ".repeat(level);
      negatedFields.push(`\n${indent}${propertyName(name)}?: never;\n${closingIndent}`);
    }
  }
  if (negatedFields.length === 0) {
    throw new TypeError("Conditional schema must constrain at least one property");
  }

  const matching = `(${schemaType(condition, level + 1, undefined, componentSchemasValue)}) & (${schemaType(thenSchema, level + 1, undefined, componentSchemasValue)})`;
  const alternate = negatedFields
    .map(
      (fields) =>
        `({${fields}})${schema.else === undefined ? "" : ` & (${schemaType(schema.else, level + 1, undefined, componentSchemasValue)})`}`,
    )
    .join(" | ");
  return `((${matching}) | (${alternate}))`;
}

function schemaProperty(schemaValue, name, componentSchemas, visitedReferences) {
  const schema = assertRecord(schemaValue, "allOf schema");
  if (typeof schema.$ref === "string") {
    if (visitedReferences.has(schema.$ref)) return undefined;
    const schemaName = schemaNameFromReference(schema.$ref);
    if (schemaName === undefined) return undefined;
    const referencedSchema = componentSchemas[schemaName];
    if (referencedSchema === undefined) return undefined;
    return schemaProperty(
      referencedSchema,
      name,
      componentSchemas,
      new Set([...visitedReferences, schema.$ref]),
    );
  }

  if (schema.properties !== undefined) {
    const property = assertRecord(schema.properties, "allOf properties")[name];
    if (property !== undefined) return property;
  }
  if (Array.isArray(schema.allOf)) {
    return resolveAllOfPropertySchema(schema.allOf, name, componentSchemas, visitedReferences);
  }
  return undefined;
}

export function resolveAllOfPropertySchema(
  schemaValues,
  name,
  componentSchemasValue = {},
  visitedReferences = new Set(),
) {
  if (!Array.isArray(schemaValues)) throw new TypeError("allOf schemas must be an array");
  if (typeof name !== "string") throw new TypeError("allOf property name must be a string");
  const componentSchemas = assertRecord(componentSchemasValue, "component schemas");
  for (const schemaValue of schemaValues) {
    const property = schemaProperty(schemaValue, name, componentSchemas, visitedReferences);
    if (property !== undefined) return property;
  }
  return undefined;
}

export function schemaType(
  schemaValue,
  level = 0,
  enclosingSchemaValue,
  componentSchemasValue = {},
  inheritedSchemaValues = [],
) {
  if (schemaValue === undefined) return "unknown";
  const schema = assertRecord(schemaValue, "schema");
  const componentSchemas = assertRecord(componentSchemasValue, "component schemas");
  if (typeof schema.$ref === "string") return referenceType(schema.$ref);
  if (Array.isArray(schema.enum))
    return schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.if !== undefined)
    return conditionalType(schema, enclosingSchemaValue, level, componentSchemas);

  const combinations = [
    ["allOf", " & "],
    ["anyOf", " | "],
    ["oneOf", " | "],
  ];
  for (const [key, separator] of combinations) {
    if (Array.isArray(schema[key])) {
      const base = { ...schema };
      delete base[key];
      const combined = schema[key]
        .map(
          (part, index, parts) =>
            `(${schemaType(
              part,
              level + 1,
              key === "allOf" ? base : undefined,
              componentSchemas,
              key === "allOf" ? [base, ...parts.filter((_, partIndex) => partIndex !== index)] : [],
            )})`,
        )
        .join(separator);
      if (
        schema.type === "object" ||
        schema.properties !== undefined ||
        schema.additionalProperties !== undefined
      ) {
        return `(${schemaType(base, level, undefined, componentSchemas)}) & (${combined})`;
      }
      return combined;
    }
  }

  if (Array.isArray(schema.type)) {
    return schema.type
      .map((type) =>
        schemaType(
          { ...schema, type, enum: undefined },
          level,
          undefined,
          componentSchemas,
          inheritedSchemaValues,
        ),
      )
      .filter((value, index, values) => values.indexOf(value) === index)
      .join(" | ");
  }
  if (schema.type === "null") return "null";
  if (schema.type === "string") return "string";
  if (schema.type === "integer" || schema.type === "number") return "number";
  if (schema.type === "boolean") return "boolean";
  if (schema.type === "array") {
    const itemType = schemaType(schema.items, level + 1, undefined, componentSchemas);
    // `minItems: 1` is deliberately NOT emitted as a non-empty tuple. A tuple
    // rejects every array built at runtime — `rows.map(...)` is the SDK's
    // primary send path — with "Source provides no match for required element
    // at position 0", which never mentions emptiness and has no fix but a
    // cast. Non-emptiness is enforced at the resource boundary instead
    // (assertNonEmptyArray in src/resources/_helpers.ts), which also covers
    // JavaScript callers.
    return schema.minItems === 1 ? `ReadonlyArray<${itemType}>` : `Array<${itemType}>`;
  }

  if (
    schema.type === "object" ||
    schema.properties !== undefined ||
    schema.additionalProperties !== undefined
  ) {
    const properties =
      schema.properties === undefined ? {} : assertRecord(schema.properties, "properties");
    const required = new Set(
      Array.isArray(schema.required)
        ? schema.required.filter((name) => typeof name === "string")
        : [],
    );
    const indent = "  ".repeat(level + 1);
    const closingIndent = "  ".repeat(level);
    const propertyNames = [
      ...Object.keys(properties),
      ...[...required].filter((name) => !Object.hasOwn(properties, name)),
    ];
    const fields = propertyNames.map((name) => {
      const value =
        properties[name] ??
        resolveAllOfPropertySchema(inheritedSchemaValues, name, componentSchemas);
      return `${indent}${propertyName(name)}${required.has(name) ? "" : "?"}: ${value === undefined ? "unknown" : schemaType(value, level + 1, undefined, componentSchemas)};`;
    });
    if (schema.additionalProperties === true) fields.push(`${indent}[key: string]: unknown;`);
    else if (schema.additionalProperties !== undefined && schema.additionalProperties !== false) {
      fields.push(
        `${indent}[key: string]: ${schemaType(
          schema.additionalProperties,
          level + 1,
          undefined,
          componentSchemas,
        )};`,
      );
    }
    return fields.length === 0
      ? "Record<string, never>"
      : `{\n${fields.join("\n")}\n${closingIndent}}`;
  }
  return "unknown";
}

function operationType(document, entry, componentSchemas) {
  const pathItem = assertRecord(assertRecord(document.paths, "paths")[entry.path], entry.path);
  const parameters = operationParameters(pathItem, entry.operation)
    .map((parameter) => dereferenceParameter(document, parameter))
    .filter((parameter) => parameter.name !== "Idempotency-Key");
  const byLocation = new Map();
  for (const parameter of parameters) {
    if (typeof parameter.in !== "string" || typeof parameter.name !== "string") continue;
    const list = byLocation.get(parameter.in) ?? [];
    list.push(parameter);
    byLocation.set(parameter.in, list);
  }
  const parameterFields = [];
  for (const location of ["path", "query", "header"]) {
    const values = byLocation.get(location);
    if (values === undefined || values.length === 0) continue;
    const fields = values.map(
      (parameter) =>
        `        ${propertyName(parameter.name)}${parameter.required === true ? "" : "?"}: ${schemaType(parameter.schema, 4, undefined, componentSchemas)};`,
    );
    parameterFields.push(`      ${location}: {\n${fields.join("\n")}\n      };`);
  }

  const lines = ["  {", "    parameters: {"];
  lines.push(
    ...(parameterFields.length > 0 ? parameterFields : ["      path?: Record<string, never>;"]),
  );
  lines.push("    };");
  if (entry.operation.requestBody !== undefined) {
    const requestBody = assertRecord(
      entry.operation.requestBody,
      `${entry.operationId}.requestBody`,
    );
    const content = assertRecord(requestBody.content, `${entry.operationId}.requestBody.content`);
    const media = assertRecord(content[JSON_CONTENT_TYPE], `${entry.operationId} JSON body`);
    lines.push(
      `    requestBody${requestBody.required === true ? "" : "?"}: { content: { \"application/json\": ${schemaType(media.schema, 3, undefined, componentSchemas)} } };`,
    );
  }
  lines.push("    responses: {");
  for (const [status, responseValue] of Object.entries(
    assertRecord(entry.operation.responses, "responses"),
  )) {
    const response = dereferenceResponse(document, responseValue);
    const content = response.content;
    if (content === undefined) lines.push(`      ${propertyName(status)}: { content?: never };`);
    else {
      const media = assertRecord(
        assertRecord(content, "response content")[JSON_CONTENT_TYPE],
        "response JSON",
      );
      lines.push(
        `      ${propertyName(status)}: { content: { \"application/json\": ${schemaType(media.schema, 4, undefined, componentSchemas)} } };`,
      );
    }
  }
  lines.push("    };", "  }");
  return lines.join("\n");
}

function generateRestTypes(document, operations) {
  const schemas = assertRecord(assertRecord(document.components, "components").schemas, "schemas");
  const lines = [GENERATED_HEADER.trimEnd(), "export interface paths {"];
  const paths = new Map();
  for (const entry of operations) {
    const pathOperations = paths.get(entry.path) ?? [];
    pathOperations.push(entry);
    paths.set(entry.path, pathOperations);
  }
  for (const [path, entries] of paths) {
    const methods = entries
      .map((entry) => `${entry.method}: operations[${JSON.stringify(entry.operationId)}]`)
      .join("; ");
    lines.push(`  ${JSON.stringify(path)}: { ${methods} };`);
  }
  lines.push("}", "", "export interface components {", "  schemas: {");
  for (const [name, schema] of Object.entries(schemas)) {
    lines.push(`    ${propertyName(name)}: ${schemaType(schema, 2, undefined, schemas)};`);
  }
  lines.push("  };", "}", "", "export interface operations {");
  for (const entry of operations) {
    lines.push(`  ${propertyName(entry.operationId)}: ${operationType(document, entry, schemas)};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function webhookSchemaName(webhookName, webhookValue) {
  const webhook = assertRecord(webhookValue, `webhook ${webhookName}`);
  const operation = assertRecord(webhook.post, `webhook ${webhookName} POST operation`);
  const body = assertRecord(operation.requestBody, `webhook ${webhookName} requestBody`);
  const content = assertRecord(body.content, `webhook ${webhookName} requestBody.content`);
  const media = assertRecord(content[JSON_CONTENT_TYPE], `webhook ${webhookName} JSON body`);
  const schema = assertRecord(media.schema, `webhook ${webhookName} schema`);
  const name = schemaNameFromReference(schema.$ref);
  if (name === undefined) {
    throw new TypeError(`Webhook ${webhookName} must reference a component schema`);
  }
  return name;
}

// `format: email` is descriptive of what AhaSend intends to send, not a
// contract a receiver may enforce. Real deliveries carry display-name
// mailboxes ("Acme <news@example.com>" from campaigns), SMTPUTF8 addresses,
// and — on inbound routes — whatever an arbitrary external sender used.
// Rejecting those returns 400 to AhaSend, and 100 consecutive 400s disable
// the webhook entirely, so an over-strict receiver turns a benign producer
// change into an outage. Structural formats (`uuid`, `date-time`) stay
// enforced because they discriminate the envelope.
const UNENFORCED_WEBHOOK_FORMATS = new Set(["email"]);

export function validationSchema(schemaValue) {
  const schema = assertRecord(schemaValue, "webhook validation schema");
  const result = {};
  for (const key of ["$ref", "type", "format", "enum", "required", "additionalProperties"]) {
    if (schema[key] === undefined) continue;
    if (key === "format" && UNENFORCED_WEBHOOK_FORMATS.has(schema[key])) continue;
    result[key] = schema[key];
  }
  if (schema.properties !== undefined) {
    result.properties = Object.fromEntries(
      Object.entries(assertRecord(schema.properties, "webhook schema properties")).map(
        ([name, value]) => [name, validationSchema(value)],
      ),
    );
  }
  if (schema.items !== undefined) result.items = validationSchema(schema.items);
  for (const key of ["allOf", "anyOf", "oneOf"]) {
    if (schema[key] !== undefined) {
      if (!Array.isArray(schema[key])) throw new TypeError(`${key} must be an array`);
      result[key] = schema[key].map((value) => validationSchema(value));
    }
  }
  if (
    result.additionalProperties !== undefined &&
    typeof result.additionalProperties !== "boolean"
  ) {
    result.additionalProperties = validationSchema(result.additionalProperties);
  }
  return result;
}

function webhookObjectShape(schemaValue, schemas, seen = new Set()) {
  const schema = assertRecord(schemaValue, "webhook object schema");
  if (typeof schema.$ref === "string") {
    const name = schemaNameFromReference(schema.$ref);
    if (name === undefined || seen.has(name)) {
      throw new TypeError(`Unsupported webhook schema reference ${schema.$ref}`);
    }
    const referenced = schemas[name];
    if (referenced === undefined) throw new TypeError(`Unknown webhook schema ${name}`);
    return webhookObjectShape(referenced, schemas, new Set([...seen, name]));
  }

  const required = new Set(
    Array.isArray(schema.required)
      ? schema.required.filter((name) => typeof name === "string")
      : [],
  );
  const properties = new Map();
  if (schema.properties !== undefined) {
    for (const [name, value] of Object.entries(
      assertRecord(schema.properties, "webhook object properties"),
    )) {
      properties.set(name, [value]);
    }
  }
  if (schema.allOf !== undefined) {
    if (!Array.isArray(schema.allOf)) throw new TypeError("Webhook allOf must be an array");
    for (const part of schema.allOf) {
      const shape = webhookObjectShape(part, schemas, seen);
      for (const name of shape.required) required.add(name);
      for (const [name, values] of shape.properties) {
        properties.set(name, [...(properties.get(name) ?? []), ...values]);
      }
    }
  }
  if (schema.type !== undefined && schema.type !== "object") {
    throw new TypeError("Webhook envelope schemas must describe objects");
  }
  return { required, properties };
}

function referencedSchemaType(schemaValue, schemas, seen = new Set()) {
  const schema = assertRecord(schemaValue, "webhook property schema");
  if (typeof schema.$ref !== "string") return schema.type;
  const name = schemaNameFromReference(schema.$ref);
  if (name === undefined || seen.has(name)) {
    throw new TypeError(`Unsupported webhook property reference ${schema.$ref}`);
  }
  const referenced = schemas[name];
  if (referenced === undefined) throw new TypeError(`Unknown webhook schema ${name}`);
  return referencedSchemaType(referenced, schemas, new Set([...seen, name]));
}

function commonWebhookEnvelopeSchema(webhooks, schemas) {
  const shapes = Object.entries(webhooks).map(([eventType, webhook]) => {
    const schemaName = webhookSchemaName(eventType, webhook);
    const schema = schemas[schemaName];
    if (schema === undefined) throw new TypeError(`Unknown webhook schema ${schemaName}`);
    return webhookObjectShape(schema, schemas, new Set([schemaName]));
  });
  const commonFields = ["type", "timestamp", "data"];
  for (const field of commonFields) {
    if (shapes.some((shape) => !shape.required.has(field) || !shape.properties.has(field))) {
      throw new TypeError(`Every webhook schema must require common envelope field ${field}`);
    }
  }

  const timestampSchemas = shapes.map((shape) => {
    const candidates = shape.properties.get("timestamp") ?? [];
    const candidate = candidates.find(
      (value) => assertRecord(value, "webhook timestamp schema").type === "string",
    );
    if (candidate === undefined) throw new TypeError("Webhook timestamp must be a string");
    return validationSchema(candidate);
  });
  const timestampSchema = timestampSchemas[0];
  if (
    timestampSchema === undefined ||
    timestampSchemas.some((schema) => JSON.stringify(schema) !== JSON.stringify(timestampSchema))
  ) {
    throw new TypeError("Webhook timestamp schemas must share one common definition");
  }
  for (const shape of shapes) {
    const typeCandidates = shape.properties.get("type") ?? [];
    if (
      !typeCandidates.some((value) => assertRecord(value, "webhook type schema").type === "string")
    ) {
      throw new TypeError("Webhook type must be a string");
    }
    const dataCandidates = shape.properties.get("data") ?? [];
    if (!dataCandidates.some((value) => referencedSchemaType(value, schemas) === "object")) {
      throw new TypeError("Webhook data must be an object");
    }
  }

  return {
    type: "object",
    required: commonFields,
    properties: {
      type: { type: "string" },
      timestamp: timestampSchema,
      data: { type: "object" },
    },
  };
}

function generateWebhookTypes(document, webhookDigest) {
  const webhooks = assertRecord(document.webhooks, "Webhook definitions");
  const schemas = assertRecord(
    assertRecord(document.components, "Webhook components").schemas,
    "Webhook schemas",
  );
  const entries = Object.entries(webhooks).map(([eventType, webhook]) => [
    eventType,
    webhookSchemaName(eventType, webhook),
  ]);
  const deprecatedTypes = [
    ...new Set(
      Object.values(schemas).flatMap((schemaValue) => {
        const schema = assertRecord(schemaValue, "webhook schema");
        const properties = schema.properties;
        if (properties === undefined) return [];
        const typeValue = assertRecord(properties, "webhook schema properties").type;
        if (typeValue === undefined) return [];
        const typeSchema = assertRecord(typeValue, "webhook type schema");
        const values = typeSchema["x-deprecated-values"];
        return Array.isArray(values) ? values.filter((value) => typeof value === "string") : [];
      }),
    ),
  ];
  const canonicalTypes = entries.map(([eventType]) => eventType);
  const knownTypes = [...canonicalTypes, ...deprecatedTypes];
  const lines = [
    `${GENERATED_HEADER.trimEnd()} Source webhooks.yaml SHA-256: ${webhookDigest}`,
    "",
    `export const WEBHOOK_CONTRACT_SHA256 = ${JSON.stringify(webhookDigest)} as const;`,
    "",
    `export const WEBHOOK_SCHEMA_NAMES = ${JSON.stringify(Object.keys(schemas))} as const;`,
    `export const CANONICAL_WEBHOOK_EVENT_TYPES = ${JSON.stringify(canonicalTypes)} as const;`,
    `export const DEPRECATED_WEBHOOK_EVENT_TYPES = ${JSON.stringify(deprecatedTypes)} as const;`,
    `export const KNOWN_WEBHOOK_EVENT_TYPES = ${JSON.stringify(knownTypes)} as const;`,
    "",
    "export type CanonicalWebhookEventType = (typeof CANONICAL_WEBHOOK_EVENT_TYPES)[number];",
    "export type DeprecatedWebhookEventType = (typeof DEPRECATED_WEBHOOK_EVENT_TYPES)[number];",
    "export type WebhookEventType = (typeof KNOWN_WEBHOOK_EVENT_TYPES)[number];",
    "",
    "export interface components {",
    "  schemas: {",
  ];
  for (const [name, schema] of Object.entries(schemas)) {
    lines.push(`    ${propertyName(name)}: ${schemaType(schema, 2, undefined, schemas)};`);
  }
  lines.push("  };", "}", "", "export interface webhookEvents {");
  for (const [eventType, schemaName] of entries) {
    lines.push(
      `  ${JSON.stringify(eventType)}: components["schemas"][${JSON.stringify(schemaName)}];`,
    );
  }
  lines.push(
    "}",
    "",
    "export type KnownWebhookEvent = webhookEvents[keyof webhookEvents];",
    "export type WebhookEvent = KnownWebhookEvent;",
    "",
    "export interface UnknownWebhookEvent {",
    "  type: string & { readonly __aha_unknown__?: never };",
    "  timestamp: string;",
    "  data: unknown;",
    "  [key: string]: unknown;",
    "}",
    "",
    "export type AnyWebhookEvent = KnownWebhookEvent | UnknownWebhookEvent;",
    "",
  );
  return lines.join("\n");
}

function generateWebhookValidators(document) {
  const webhooks = assertRecord(document.webhooks, "Webhook definitions");
  const schemas = assertRecord(
    assertRecord(document.components, "Webhook components").schemas,
    "Webhook schemas",
  );
  const eventSchemas = Object.fromEntries(
    Object.entries(webhooks).map(([eventType, webhook]) => [
      eventType,
      webhookSchemaName(eventType, webhook),
    ]),
  );
  const routeSchemaName = eventSchemas["message.routing"];
  if (routeSchemaName === undefined) throw new TypeError("message.routing webhook is required");
  eventSchemas["route.message"] = routeSchemaName;
  const normalizedSchemas = Object.fromEntries(
    Object.entries(schemas).map(([name, schema]) => [name, validationSchema(schema)]),
  );
  const commonEnvelopeSchema = commonWebhookEnvelopeSchema(webhooks, schemas);

  return `${GENERATED_HEADER}import {
  KNOWN_WEBHOOK_EVENT_TYPES,
  WEBHOOK_CONTRACT_SHA256,
  type AnyWebhookEvent,
  type KnownWebhookEvent,
  type UnknownWebhookEvent,
  type WebhookEventType,
} from "./webhook-types.js";

export { WEBHOOK_CONTRACT_SHA256 };

interface ValidationSchema {
  readonly $ref?: string;
  readonly type?: string | readonly string[];
  readonly format?: string;
  readonly enum?: readonly unknown[];
  readonly required?: readonly string[];
  readonly properties?: Readonly<Record<string, ValidationSchema>>;
  readonly items?: ValidationSchema;
  readonly additionalProperties?: boolean | ValidationSchema;
  readonly allOf?: readonly ValidationSchema[];
  readonly anyOf?: readonly ValidationSchema[];
  readonly oneOf?: readonly ValidationSchema[];
}

const SCHEMA_REFERENCE_PREFIX = "#/components/schemas/";
const KNOWN_TYPES = new Set<string>(KNOWN_WEBHOOK_EVENT_TYPES);
const EVENT_SCHEMAS = ${JSON.stringify(eventSchemas, null, 2)} as const;
const SCHEMAS = ${JSON.stringify(normalizedSchemas, null, 2)} as unknown as Readonly<
  Record<string, ValidationSchema>
>;
const COMMON_ENVELOPE_SCHEMA = ${JSON.stringify(commonEnvelopeSchema, null, 2)} as const satisfies ValidationSchema;

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function matchesFormat(value: string, format: string | undefined): boolean {
  if (format === "uuid") {
    return /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(value);
  }
  if (format === "date-time") {
    if (
      !/^\\d{4}-\\d{2}-\\d{2}[Tt]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?(?:[Zz]|[+-]\\d{2}:\\d{2})$/.test(
        value,
      )
    ) {
      return false;
    }
    const year = Number(value.slice(0, 4));
    const month = Number(value.slice(5, 7));
    const day = Number(value.slice(8, 10));
    const hour = Number(value.slice(11, 13));
    const minute = Number(value.slice(14, 16));
    const second = Number(value.slice(17, 19));
    if (month < 1 || month > 12 || hour > 23 || minute > 59 || second > 60) return false;
    const leapYear = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
    const daysInMonth =
      month === 2 ? (leapYear ? 29 : 28) : month === 4 || month === 6 || month === 9 || month === 11 ? 30 : 31;
    if (day < 1 || day > daysInMonth) return false;
    const usesZuluOffset = /[Zz]$/.test(value);
    const offsetHour = usesZuluOffset ? 0 : Number(value.slice(-5, -3));
    const offsetMinute = usesZuluOffset ? 0 : Number(value.slice(-2));
    if (offsetHour > 23 || offsetMinute > 59) return false;
    if (second < 60) return true;

    // RFC 3339 permits :60 only at an inserted leap second. Normalize the
    // preceding local second to UTC so numeric-offset representations work too.
    const offsetSign = !usesZuluOffset && value.slice(-6, -5) === "-" ? -1 : 1;
    const leapSecond = new Date(0);
    leapSecond.setUTCFullYear(year, month - 1, day);
    leapSecond.setUTCHours(hour, minute - offsetSign * (offsetHour * 60 + offsetMinute), 59, 0);
    return (
      ((leapSecond.getUTCMonth() === 5 && leapSecond.getUTCDate() === 30) ||
        (leapSecond.getUTCMonth() === 11 && leapSecond.getUTCDate() === 31)) &&
      leapSecond.getUTCHours() === 23 &&
      leapSecond.getUTCMinutes() === 59
    );
  }
  return true;
}

function matchesType(value: unknown, type: string, schema: ValidationSchema): boolean {
  if (type === "null") return value === null;
  if (type === "string") return typeof value === "string" && matchesFormat(value, schema.format);
  if (type === "boolean") return typeof value === "boolean";
  if (type === "number") return typeof value === "number" && Number.isFinite(value);
  if (type === "integer") return typeof value === "number" && Number.isInteger(value);
  if (type === "array") {
    if (!Array.isArray(value)) return false;
    const itemSchema = schema.items;
    return itemSchema === undefined || value.every((item) => matchesSchema(item, itemSchema));
  }
  if (type === "object") return isRecord(value) && matchesObject(value, schema);
  return true;
}

function matchesObject(value: Record<string, unknown>, schema: ValidationSchema): boolean {
  if (schema.required?.some((name) => !Object.hasOwn(value, name)) === true) return false;
  const properties = schema.properties ?? {};
  for (const [name, propertySchema] of Object.entries(properties)) {
    if (Object.hasOwn(value, name) && !matchesSchema(value[name], propertySchema)) return false;
  }
  const additionalProperties = schema.additionalProperties;
  if (additionalProperties === undefined || additionalProperties === true) return true;
  const extraNames = Object.keys(value).filter((name) => !Object.hasOwn(properties, name));
  if (additionalProperties === false) return extraNames.length === 0;
  return extraNames.every((name) => matchesSchema(value[name], additionalProperties));
}

function matchesSchema(value: unknown, schema: ValidationSchema): boolean {
  if (schema.$ref !== undefined) {
    if (!schema.$ref.startsWith(SCHEMA_REFERENCE_PREFIX)) return false;
    const referenced = SCHEMAS[schema.$ref.slice(SCHEMA_REFERENCE_PREFIX.length)];
    return referenced !== undefined && matchesSchema(value, referenced);
  }
  if (schema.allOf?.every((part) => matchesSchema(value, part)) === false) return false;
  if (schema.anyOf !== undefined && !schema.anyOf.some((part) => matchesSchema(value, part))) {
    return false;
  }
  if (
    schema.oneOf !== undefined &&
    schema.oneOf.filter((part) => matchesSchema(value, part)).length !== 1
  ) {
    return false;
  }
  if (schema.enum !== undefined && !schema.enum.some((item) => Object.is(item, value))) return false;
  if (schema.type === undefined) return true;
  const types = typeof schema.type === "string" ? [schema.type] : schema.type;
  return types.some((type) => matchesType(value, type, schema));
}

export function isKnownWebhookEventType(value: unknown): value is WebhookEventType {
  return typeof value === "string" && KNOWN_TYPES.has(value);
}

export function validateKnownWebhookEvent(value: unknown): value is KnownWebhookEvent {
  if (!isRecord(value) || !isKnownWebhookEventType(value.type)) return false;
  const schemaName = EVENT_SCHEMAS[value.type];
  const schema = SCHEMAS[schemaName];
  return schema !== undefined && matchesSchema(value, schema);
}

export function validateUnknownWebhookEvent(value: unknown): value is UnknownWebhookEvent {
  return (
    matchesSchema(value, COMMON_ENVELOPE_SCHEMA) &&
    isRecord(value) &&
    !isKnownWebhookEventType(value.type)
  );
}

export function validateWebhookEvent(value: unknown): value is AnyWebhookEvent {
  return validateKnownWebhookEvent(value) || validateUnknownWebhookEvent(value);
}
`;
}

function securityAlternatives(operation, document) {
  const security = Array.isArray(operation.security) ? operation.security : document.security;
  if (!Array.isArray(security)) return [];
  return security.map((requirementValue) => {
    const requirement = assertRecord(requirementValue, "security requirement");
    const roles = requirement.BearerAuth;
    if (!Array.isArray(roles) || !roles.every((role) => typeof role === "string")) {
      throw new TypeError("BearerAuth security requirements must contain string roles");
    }
    return roles;
  });
}

function bodyFact(operation) {
  if (operation.requestBody === undefined) return null;
  const body = assertRecord(operation.requestBody, "requestBody");
  const media = assertRecord(
    assertRecord(body.content, "requestBody.content")[JSON_CONTENT_TYPE],
    "JSON body",
  );
  const schema = assertRecord(media.schema, "request body schema");
  return {
    required: body.required === true,
    schema: schemaNameFromReference(schema.$ref) ?? "inline",
  };
}

function successFacts(document, operation) {
  const facts = [];
  for (const [status, responseValue] of Object.entries(
    assertRecord(operation.responses, "responses"),
  )) {
    if (!/^2\d\d$/.test(status)) continue;
    const response = dereferenceResponse(document, responseValue);
    const content = response.content;
    let schema = null;
    if (content !== undefined) {
      const media = assertRecord(
        assertRecord(content, "response content")[JSON_CONTENT_TYPE],
        "response JSON",
      );
      const responseSchema = assertRecord(media.schema, "response schema");
      schema = schemaNameFromReference(responseSchema.$ref) ?? "inline";
    }
    facts.push({ status: Number(status), schema });
  }
  if (facts.length === 0) throw new TypeError("Operation has no 2xx response");
  return facts;
}

function retryMode(method, idempotency) {
  if (method === "get") return "safe";
  if (method === "put" || method === "delete") return "idempotent";
  if (idempotency) return "idempotency_key";
  return "never";
}

function parameterFact(parameter) {
  const schema = assertRecord(parameter.schema, `parameter ${parameter.name} schema`);
  return {
    name: parameter.name,
    required: parameter.required === true,
    format: typeof schema.format === "string" ? schema.format : null,
  };
}

function generateOperations(document, operations) {
  validateAuthorizationRegistry(document);
  const descriptors = {};
  for (const entry of operations) {
    const pathItem = assertRecord(assertRecord(document.paths, "paths")[entry.path], entry.path);
    const parameters = operationParameters(pathItem, entry.operation).map((parameter) =>
      dereferenceParameter(document, parameter),
    );
    const pathParameters = parameters
      .filter((parameter) => parameter.in === "path")
      .map(parameterFact);
    const query = parameters.filter((parameter) => parameter.in === "query").map(parameterFact);
    const idempotency = parameters.some((parameter) => parameter.name === "Idempotency-Key");
    descriptors[entry.operationId] = {
      method: entry.method.toUpperCase(),
      path: entry.path,
      pathParameters,
      query,
      body: bodyFact(entry.operation),
      success: successFacts(document, entry.operation),
      idempotency,
      retry: retryMode(entry.method, idempotency),
      security: securityAlternatives(entry.operation, document),
      resourceAuthorization: AUTHORIZATION_REGISTRY[entry.operationId] ?? null,
    };
  }

  return `${GENERATED_HEADER}import type { operations } from "./rest-types.js";

export type RetryMode = "safe" | "idempotent" | "idempotency_key" | "never";

interface ResourceAuthorizationMetadata {
  readonly roles: {
    readonly global: string;
    readonly domain: string;
  };
  readonly summary: string;
}

export type ResourceAuthorizationRule = ResourceAuthorizationMetadata &
  (
  | {
      readonly kind: "body_domain";
      readonly bodyPath: "from.email" | "recipient";
      readonly quantifier: "one";
    }
  | {
      readonly kind: "query_domain_required_for_scoped";
      readonly queryParameter: "domain";
      readonly condition: "scoped_role_requires_filter";
    }
  | {
      readonly kind: "existing_and_replacement_domain";
      readonly resource: "route";
      readonly resourceIdParameter: "route_id";
      readonly existingPath: "recipient";
      readonly replacementBodyPath: "recipient";
      readonly quantifier: "every";
    }
  | {
      readonly kind: "all_body_domains";
      readonly bodyPath: "domains";
      readonly scopeBodyPath: "scope";
      readonly globalValue: "global";
      readonly quantifier: "every";
      readonly condition: "global_scope_requires_global_role";
    }
  | {
      readonly kind: "existing_and_new_domains";
      readonly resource: "webhook";
      readonly resourceIdParameter: "webhook_id";
      readonly existingPath: "domains";
      readonly newBodyPath: "domains";
      readonly scopeBodyPath: "scope";
      readonly globalValue: "global";
      readonly quantifier: "every";
      readonly transition: "global_scope_requires_global_role";
    }
  | {
      readonly kind: "comma_separated_query_domains";
      readonly queryParameter: "sender_domain";
      readonly quantifier: "every";
    }
  | {
      readonly kind: "authorized_domain_filter";
      readonly resource: "message" | "webhook" | "smtp_credential";
      readonly resourceDomainPath: "sender" | "domains";
      readonly quantifier: "one" | "at_least_one";
    }
  | {
      readonly kind: "existing_resource_domains";
      readonly resource: "message" | "route" | "webhook" | "smtp_credential";
      readonly resourceIdParameter:
        | "message_id"
        | "route_id"
        | "webhook_id"
        | "smtp_credential_id";
      readonly resourceDomainPath: "sender" | "recipient" | "domains";
      readonly quantifier: "one" | "at_least_one";
    }
  );

export interface OperationDescriptor {
  readonly method: "GET" | "POST" | "PUT" | "DELETE";
  readonly path: string;
  readonly pathParameters: readonly ParameterDescriptor[];
  readonly query: readonly ParameterDescriptor[];
  readonly body: { readonly required: boolean; readonly schema: string } | null;
  readonly success: readonly { readonly status: number; readonly schema: string | null }[];
  readonly idempotency: boolean;
  readonly retry: RetryMode;
  readonly security: readonly (readonly string[])[];
  readonly resourceAuthorization: ResourceAuthorizationRule | null;
}

export interface ParameterDescriptor {
  readonly name: string;
  readonly required: boolean;
  readonly format: string | null;
}

export const RESOURCE_AUTHORIZATION = ${JSON.stringify(AUTHORIZATION_REGISTRY, null, 2)} as const satisfies Readonly<
  Partial<Record<keyof typeof OPERATION_DESCRIPTORS, ResourceAuthorizationRule>>
>;

export const OPERATION_DESCRIPTORS = ${JSON.stringify(descriptors, null, 2)} as const satisfies Readonly<
  Record<string, OperationDescriptor>
>;

export type OperationId = keyof typeof OPERATION_DESCRIPTORS;

export type OperationParametersById = {
  readonly [Operation in OperationId]: operations[Operation]["parameters"];
};

export type RequestInput<Value> = Value extends readonly [infer Head, ...infer Tail]
  ? readonly [RequestInput<Head>, ...RequestInput<Tail>]
  : Value extends readonly (infer Item)[]
    ? readonly RequestInput<Item>[]
    : Value extends object
      ? { [Key in keyof Value]: RequestInput<Value[Key]> }
      : Value;

export type OperationRequestBodyById = {
  readonly [Operation in OperationId]: operations[Operation] extends {
    requestBody: { content: { "application/json": infer Body } };
  }
    ? RequestInput<Body>
    : never;
};

export type OperationInputById = {
  readonly [Operation in OperationId]: OperationParametersById[Operation] &
    (OperationRequestBodyById[Operation] extends never
      ? { body?: never }
      : { body: OperationRequestBodyById[Operation] });
};

type JsonSuccess<ResponseMap> = {
  [Status in keyof ResponseMap]: Status extends \`2\${string}\`
    ? ResponseMap[Status] extends {
        content: { "application/json": infer Body };
      }
      ? Body
      : never
    : never;
}[keyof ResponseMap];

export type OperationSuccessById = {
  readonly [Operation in OperationId]: JsonSuccess<operations[Operation]["responses"]>;
};
`;
}

function generateProfileTypes() {
  return `${GENERATED_HEADER}import profileJson from "./operation-profile.json";
import type { OperationId } from "./operations.js";

export interface OperationProfileMapping {
  readonly operationId: OperationId;
  readonly facade: string;
  readonly method: string;
}

export interface OperationProfile {
  readonly version: 1;
  readonly operations: readonly OperationProfileMapping[];
  readonly iterators: readonly OperationProfileMapping[];
}

// JSON is the canonical table. This module only supplies its checked TypeScript view.
export const OPERATION_PROFILE = profileJson as unknown as OperationProfile;
`;
}

function generateContractDigests(openApiDigest, webhookDigest, profileDigest) {
  return `${GENERATED_HEADER}export const OPENAPI_SHA256 = ${JSON.stringify(openApiDigest)} as const;
export const WEBHOOK_SHA256 = ${JSON.stringify(webhookDigest)} as const;
export const OPERATION_PROFILE_SHA256 = ${JSON.stringify(profileDigest)} as const;

export const CONTRACT_DIGESTS = Object.freeze({
  openapi: OPENAPI_SHA256,
  webhooks: WEBHOOK_SHA256,
  operationProfile: OPERATION_PROFILE_SHA256,
});
`;
}

export async function generateSdkArtifacts(openApiSource, webhookSource) {
  const document = parseOpenApi(openApiSource);
  const webhookDocument = parseWebhookContract(webhookSource);
  validateWebhookContract(webhookDocument);
  const operations = collectOperations(document);
  const schemas = Object.keys(
    assertRecord(assertRecord(document.components, "components").schemas, "schemas"),
  );
  if (operations.length !== EXPECTED_OPERATION_COUNT || schemas.length !== EXPECTED_SCHEMA_COUNT) {
    throw new TypeError(
      `Expected ${EXPECTED_OPERATION_COUNT} operations and ${EXPECTED_SCHEMA_COUNT} schemas; received ${operations.length} and ${schemas.length}`,
    );
  }
  const webhookCount = Object.keys(
    assertRecord(webhookDocument.webhooks, "Webhook definitions"),
  ).length;
  const webhookSchemaCount = Object.keys(
    assertRecord(
      assertRecord(webhookDocument.components, "Webhook components").schemas,
      "Webhook schemas",
    ),
  ).length;
  if (
    webhookCount !== EXPECTED_WEBHOOK_COUNT ||
    webhookSchemaCount !== EXPECTED_WEBHOOK_SCHEMA_COUNT
  ) {
    throw new TypeError(
      `Expected ${EXPECTED_WEBHOOK_COUNT} webhooks and ${EXPECTED_WEBHOOK_SCHEMA_COUNT} webhook schemas; received ${webhookCount} and ${webhookSchemaCount}`,
    );
  }
  const profile = createProfile(document);
  const profileDigest = digestJsonArtifact(profile);
  const webhookDigest = digestYamlArtifact(Buffer.from(webhookSource, "utf8"));
  const profileJson = `${JSON.stringify(profile, null, 2)}\n`;
  const prettierConfig = (await resolveConfig(resolve(repositoryRoot, ".prettierrc.json"))) ?? {};
  const typescriptArtifacts = await Promise.all(
    [
      [outputPaths.restTypes, generateRestTypes(document, operations)],
      [outputPaths.operations, generateOperations(document, operations)],
      [outputPaths.profileTypes, generateProfileTypes()],
      [outputPaths.webhookTypes, generateWebhookTypes(webhookDocument, webhookDigest)],
      [outputPaths.webhookValidators, generateWebhookValidators(webhookDocument)],
      [
        outputPaths.contractDigests,
        generateContractDigests(
          digestYamlArtifact(Buffer.from(openApiSource, "utf8")),
          webhookDigest,
          profileDigest,
        ),
      ],
    ].map(async ([path, source]) => [
      path,
      await format(source, { ...prettierConfig, filepath: resolve(repositoryRoot, path) }),
    ]),
  );
  return new Map([
    ...typescriptArtifacts,
    [outputPaths.profileJson, profileJson],
    [outputPaths.profileDigest, `${profileDigest}\n`],
  ]);
}

async function run(check) {
  const openApiSource = await readFile(resolve(repositoryRoot, "openapi.yaml"), "utf8");
  const webhookSource = await readFile(resolve(repositoryRoot, "webhooks.yaml"), "utf8");
  const artifacts = await generateSdkArtifacts(openApiSource, webhookSource);
  const drift = [];
  for (const [path, expected] of artifacts) {
    const absolutePath = resolve(repositoryRoot, path);
    if (check) {
      let actual;
      try {
        actual = await readFile(absolutePath, "utf8");
      } catch (error) {
        if (error !== null && typeof error === "object" && error.code === "ENOENT")
          actual = undefined;
        else throw error;
      }
      if (actual !== expected) drift.push(path);
    } else {
      await mkdir(dirname(absolutePath), { recursive: true });
      await writeFile(absolutePath, expected, "utf8");
    }
  }
  if (drift.length > 0) {
    throw new TypeError(`Generated SDK artifacts are stale: ${drift.join(", ")}`);
  }
}

async function main() {
  const arguments_ = process.argv.slice(2);
  if (arguments_.some((argument) => argument !== "--check") || arguments_.length > 1) {
    throw new TypeError("Usage: node scripts/generate-sdk.mjs [--check]");
  }
  await run(arguments_[0] === "--check");
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  main().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`generate-sdk: ${message}\n`);
    process.exitCode = 1;
  });
}
