#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { format, resolveConfig } from "prettier";
import ts from "typescript";
import { collectOperations, parseOpenApi } from "./generate-contracts.mjs";
import {
  AUTHORIZATION_REGISTRY,
  validateAuthorizationRegistry,
  validateOperationProfile,
} from "./generate-sdk.mjs";
import { canonicalizeJson, digestYamlArtifact, sha256Hex } from "./digest-artifact.mjs";
import {
  NODE_CODE_SAMPLES,
  NODE_OPERATION_KEYS,
  NODE_SAMPLE_LANGUAGE,
} from "./node-code-samples.mjs";

const EXPECTED_OPERATION_COUNT = 56;
const EXPECTED_ITERATOR_COUNT = 9;
const IDEMPOTENCY_PARAMETER = "#/components/parameters/IdempotencyKey";
const GENERATED_HEADER =
  "<!-- Generated by scripts/generate-docs.mjs. Do not edit directly. -->\n\n";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const repositoryRoot = resolve(scriptDirectory, "..");
const outputPath = "docs/api-reference.md";
const rendererHandoffPath = "docs/renderer-handoff.json";
const rendererHandoffDigestPath = "docs/renderer-handoff.sha256";

function record(value, location) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${location} must be a mapping`);
  }
  return value;
}

function array(value, location) {
  if (!Array.isArray(value)) throw new TypeError(`${location} must be an array`);
  return value;
}

function resolveReference(document, reference) {
  if (typeof reference !== "string" || !reference.startsWith("#/")) {
    throw new TypeError(`Unsupported OpenAPI reference: ${String(reference)}`);
  }

  let value = document;
  for (const token of reference
    .slice(2)
    .split("/")
    .map((part) => part.replaceAll("~1", "/").replaceAll("~0", "~"))) {
    value = record(value, reference)[token];
    if (value === undefined) throw new TypeError(`Unresolved OpenAPI reference: ${reference}`);
  }
  return value;
}

function dereference(document, value, location) {
  const entry = record(value, location);
  return entry.$ref === undefined
    ? entry
    : record(resolveReference(document, entry.$ref), `${location} reference`);
}

function operationParameters(document, entry) {
  const pathItem = record(record(document.paths, "OpenAPI paths")[entry.path], entry.path);
  const parameters = [
    ...array(pathItem.parameters ?? [], `${entry.path} parameters`),
    ...array(entry.operation.parameters ?? [], `${entry.operationId} parameters`),
  ];
  return parameters.map((parameter, index) =>
    dereference(document, parameter, `${entry.operationId} parameter ${index}`),
  );
}

function securityAlternatives(document, operation) {
  const requirements = operation.security ?? document.security ?? [];
  if (!Array.isArray(requirements) || requirements.length === 0) return ["Anonymous"];

  return requirements.map((requirement, index) => {
    const schemes = Object.entries(record(requirement, `security alternative ${index}`));
    if (schemes.length === 0) return "Anonymous";
    return schemes
      .map(([scheme, scopesValue]) => {
        const scopes = array(scopesValue, `${scheme} scopes`);
        return scopes.length === 0
          ? `${scheme} (authentication only)`
          : `${scheme}: ${scopes.join(" + ")}`;
      })
      .join(" + ");
  });
}

function operationScopes(document, operation) {
  const scopes = new Set();
  for (const requirement of operation.security ?? document.security ?? []) {
    for (const values of Object.values(record(requirement, "security requirement"))) {
      for (const scope of array(values, "security scopes")) {
        if (typeof scope !== "string") throw new TypeError("Security scopes must be strings");
        scopes.add(scope);
      }
    }
  }
  return [...scopes];
}

function schemaName(value) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) return null;
  if (typeof value.$ref === "string") return value.$ref.split("/").at(-1) ?? null;
  return "inline schema";
}

function operationModels(document, operationId, operation) {
  const models = [];
  if (operation.requestBody !== undefined) {
    const requestBody = dereference(document, operation.requestBody, `${operationId} request body`);
    const json = record(requestBody.content, `${operationId} request content`)["application/json"];
    if (json !== undefined) {
      const name = schemaName(record(json, `${operationId} JSON request`).schema);
      if (name !== null) models.push(`request: ${name}`);
    }
  }

  for (const [status, responseValue] of Object.entries(
    record(operation.responses, `${operationId} responses`),
  )) {
    if (!/^2\d\d$/.test(status)) continue;
    const response = dereference(document, responseValue, `${operationId} response ${status}`);
    const content = response.content;
    if (content === undefined) {
      models.push(`${status}: no body`);
      continue;
    }
    const json = record(content, `${operationId} response ${status} content`)["application/json"];
    if (json === undefined) continue;
    const name = schemaName(record(json, `${operationId} JSON response ${status}`).schema);
    if (name !== null) models.push(`${status}: ${name}`);
  }
  return models;
}

function paginationFacts(document, entry) {
  const parameters = operationParameters(document, entry);
  const byName = new Map(parameters.map((parameter) => [parameter.name, parameter]));
  const after = byName.get("after");
  const before = byName.get("before");
  if (after === undefined && before === undefined) return null;
  if (after === undefined || before === undefined) {
    throw new TypeError(`${entry.operationId} must expose both after and before cursors`);
  }

  const limit = byName.get("limit");
  if (limit === undefined) throw new TypeError(`${entry.operationId} has cursors without limit`);
  const schema = dereference(document, limit.schema, `${entry.operationId} limit schema`);
  if (typeof schema.maximum !== "number") {
    throw new TypeError(`${entry.operationId} limit must declare a numeric maximum`);
  }

  return {
    maximum: schema.maximum,
    default: typeof schema.default === "number" ? schema.default : null,
  };
}

function hasIdempotency(document, entry) {
  const pathItem = record(record(document.paths, "OpenAPI paths")[entry.path], entry.path);
  return [
    ...array(pathItem.parameters ?? [], `${entry.path} parameters`),
    ...array(entry.operation.parameters ?? [], `${entry.operationId} parameters`),
  ].some(
    (parameter) =>
      parameter !== null &&
      typeof parameter === "object" &&
      !Array.isArray(parameter) &&
      parameter.$ref === IDEMPOTENCY_PARAMETER,
  );
}

function createTypeScriptContext() {
  const configPath = ts.findConfigFile(repositoryRoot, ts.sys.fileExists, "tsconfig.json");
  if (configPath === undefined) throw new TypeError("Unable to find tsconfig.json");
  const config = ts.readConfigFile(configPath, ts.sys.readFile);
  if (config.error !== undefined) {
    throw new TypeError(ts.flattenDiagnosticMessageText(config.error.messageText, "\n"));
  }
  const parsed = ts.parseJsonConfigFileContent(
    config.config,
    ts.sys,
    repositoryRoot,
    { noEmit: true },
    configPath,
  );
  const program = ts.createProgram(parsed.fileNames, parsed.options);
  const checker = program.getTypeChecker();
  const clientSource = program.getSourceFile(resolve(repositoryRoot, "src/client.ts"));
  const indexSource = program.getSourceFile(resolve(repositoryRoot, "src/index.ts"));
  if (clientSource === undefined || indexSource === undefined) {
    throw new TypeError("Unable to load the public SDK TypeScript sources");
  }
  const clientClass = clientSource.statements.find(
    (statement) => ts.isClassDeclaration(statement) && statement.name?.text === "AhaSendClient",
  );
  if (clientClass === undefined) throw new TypeError("Unable to find AhaSendClient");

  const indexSymbol = checker.getSymbolAtLocation(indexSource);
  if (indexSymbol === undefined) throw new TypeError("Unable to inspect src/index.ts exports");
  const publicModels = new Map();
  for (const exported of checker.getExportsOfModule(indexSymbol)) {
    let symbol = exported;
    if ((symbol.flags & ts.SymbolFlags.Alias) !== 0) symbol = checker.getAliasedSymbol(symbol);
    const declaration = symbol.declarations?.find((candidate) =>
      candidate.getSourceFile().fileName.startsWith(resolve(repositoryRoot, "src")),
    );
    if (declaration !== undefined) {
      publicModels.set(exported.name, declaration.getSourceFile().fileName);
    }
  }

  return {
    checker,
    clientClass,
    clientType: checker.getTypeAtLocation(clientClass),
    publicModels,
  };
}

function methodSignature(context, mapping) {
  let owner = context.clientType;
  if (mapping.facade !== "client") {
    for (const segment of mapping.facade.split(".")) {
      const property = owner.getProperty(segment);
      if (property === undefined) {
        throw new TypeError(`Profile facade ${mapping.facade} is not exposed by AhaSendClient`);
      }
      owner = context.checker.getTypeOfSymbolAtLocation(
        property,
        property.valueDeclaration ?? context.clientClass,
      );
    }
  }

  const method = owner.getProperty(mapping.method);
  if (method === undefined) {
    throw new TypeError(`Profile method ${mapping.facade}.${mapping.method} is not public`);
  }
  const declaration = method.declarations?.find((candidate) => ts.isMethodDeclaration(candidate));
  if (declaration === undefined || !ts.isMethodDeclaration(declaration)) {
    throw new TypeError(`${mapping.facade}.${mapping.method} is not a declared method`);
  }
  const methodType = context.checker.getTypeOfSymbolAtLocation(method, declaration);
  const signatures = methodType.getCallSignatures();
  if (signatures.length !== 1) {
    throw new TypeError(
      `${mapping.facade}.${mapping.method} must have exactly one public call signature`,
    );
  }
  if (declaration.type === undefined) {
    throw new TypeError(`${mapping.facade}.${mapping.method} has no declared return type`);
  }
  const parameters = declaration.parameters.map((parameter) => {
    if (parameter.type === undefined) {
      throw new TypeError(`${mapping.facade}.${mapping.method} has an untyped parameter`);
    }
    const optional = parameter.questionToken !== undefined || parameter.initializer !== undefined;
    return `${parameter.name.getText()}${optional ? "?" : ""}: ${parameter.type.getText()}`;
  });
  const signature = `(${parameters.join(", ")}): ${declaration.type.getText()}`;
  const clientPath = mapping.facade === "client" ? "client" : `client.${mapping.facade}`;
  return `${clientPath}.${mapping.method}${signature}`;
}

function modelLinks(context, signature) {
  const matches = signature.matchAll(/\b[A-Z][A-Za-z0-9_]*\b/g);
  const seen = new Set();
  const links = [];
  for (const match of matches) {
    const name = match[0];
    const source = context.publicModels.get(name);
    if (source === undefined || seen.has(name)) continue;
    seen.add(name);
    const path = relative(resolve(repositoryRoot, "docs"), source).split(sep).join("/");
    links.push(`[${name}](${path})`);
  }
  return links;
}

function renderPagination(facts) {
  if (facts === null) return null;
  const defaultText = facts.default === null ? "" : ` (default ${facts.default})`;
  return (
    `\`limit\` accepts at most ${facts.maximum} items${defaultText}. ` +
    "Pass at most one of `after` or `before`: use `pagination.next_cursor` as `after` " +
    "to move forward, or `pagination.previous_cursor` as `before` to move backward."
  );
}

function renderAuthorization(rule) {
  if (rule === undefined) {
    return [
      "- **Resource authorization:** No additional resource-aware rule beyond the security alternatives.",
      "- **Authorization rule:** `none`",
    ];
  }
  return [
    `- **Resource authorization:** ${rule.summary}`,
    `- **Authorization rule:** \`${rule.kind}\`; global role \`${rule.roles.global}\`; domain role \`${rule.roles.domain}\``,
  ];
}

function validateProfile(document, profile, operationById) {
  validateOperationProfile(document, profile);
  for (const mappingValue of profile.iterators) {
    const operationId = record(mappingValue, "iterator mapping").operationId;
    const entry = operationById.get(operationId);
    if (entry === undefined || paginationFacts(document, entry) === null) {
      throw new TypeError(`Iterator ${operationId} does not map to a paginated operation`);
    }
  }
}

export async function generateApiReference({ openApiSource, profileSource } = {}) {
  const openApi =
    openApiSource ?? (await readFile(resolve(repositoryRoot, "openapi.yaml"), "utf8"));
  const profileJson =
    profileSource ??
    (await readFile(resolve(repositoryRoot, "src/generated/operation-profile.json"), "utf8"));
  const document = parseOpenApi(openApi);
  validateAuthorizationRegistry(document);
  const profile = record(JSON.parse(profileJson), "Operation profile");
  const operations = collectOperations(document);
  const operationById = new Map(operations.map((entry) => [entry.operationId, entry]));

  validateProfile(document, profile, operationById);

  const context = createTypeScriptContext();
  const lines = [
    GENERATED_HEADER.trimEnd(),
    "",
    "# API reference",
    "",
    "This file is generated from the canonical operation profile, OpenAPI contract, " +
      "resource-authorization registry, and exported TypeScript declarations.",
    "",
    `It contains exactly ${EXPECTED_OPERATION_COUNT} API methods and ${EXPECTED_ITERATOR_COUNT} async iterators.`,
    "",
    "## Methods",
    "",
  ];

  for (const mappingValue of profile.operations) {
    const mapping = record(mappingValue, "operation mapping");
    const entry = operationById.get(mapping.operationId);
    if (entry === undefined) throw new TypeError(`Unknown operation ${mapping.operationId}`);
    const signature = methodSignature(context, mapping);
    const links = modelLinks(context, signature);
    const alternatives = securityAlternatives(document, entry.operation);
    const scopes = operationScopes(document, entry.operation);
    const models = operationModels(document, entry.operationId, entry.operation);
    const pagination = paginationFacts(document, entry);
    const authorization = AUTHORIZATION_REGISTRY[entry.operationId];

    lines.push(
      `<!-- operation: ${entry.operationId} -->`,
      `### ${mapping.facade}.${mapping.method}`,
      "",
      "```ts",
      signature,
      "```",
      "",
      `- **Operation ID:** \`${entry.operationId}\``,
      `- **HTTP:** \`${entry.method.toUpperCase()} ${entry.path}\``,
      `- **Models:** ${links.length === 0 ? "None" : links.join(", ")}`,
      `- **OpenAPI models:** ${models.length === 0 ? "None" : models.map((model) => `\`${model}\``).join(", ")}`,
      `- **Scopes:** ${scopes.length === 0 ? "None" : scopes.map((scope) => `\`${scope}\``).join(", ")}`,
      `- **Security alternatives:** ${alternatives.map((alternative) => `\`${alternative}\``).join(" **or** ")}`,
      `- **Idempotency:** ${hasIdempotency(document, entry) ? "Supported; accepts `options.idempotencyKey` and otherwise uses the SDK's automatic key." : "Not supported by this operation."}`,
      ...renderAuthorization(authorization),
    );
    if (pagination !== null) lines.push(`- **Pagination:** ${renderPagination(pagination)}`);
    lines.push("");
  }

  lines.push("## Async iterators", "");
  for (const mappingValue of profile.iterators) {
    const mapping = record(mappingValue, "iterator mapping");
    const entry = operationById.get(mapping.operationId);
    if (entry === undefined)
      throw new TypeError(`Unknown iterator operation ${mapping.operationId}`);
    const signature = methodSignature(context, mapping);
    const links = modelLinks(context, signature);
    const pagination = paginationFacts(document, entry);
    if (pagination === null) {
      throw new TypeError(`${mapping.facade}.${mapping.method} is not paginated`);
    }
    lines.push(
      `<!-- iterator: ${entry.operationId} -->`,
      `### ${mapping.facade}.${mapping.method}`,
      "",
      "```ts",
      signature,
      "```",
      "",
      `- **Operation ID:** \`${entry.operationId}\``,
      `- **Models:** ${links.length === 0 ? "None" : links.join(", ")}`,
      `- **Pagination:** ${renderPagination(pagination)}`,
      "",
    );
  }

  const source = `${lines.join("\n").trimEnd()}\n`;
  const prettierConfig = (await resolveConfig(resolve(repositoryRoot, ".prettierrc.json"))) ?? {};
  return format(source, {
    ...prettierConfig,
    filepath: resolve(repositoryRoot, outputPath),
  });
}

export async function generateRendererHandoff({ openApiSource } = {}) {
  const openApi =
    openApiSource ?? (await readFile(resolve(repositoryRoot, "openapi.yaml"), "utf8"));
  const document = parseOpenApi(openApi);
  const operations = collectOperations(document);

  if (operations.length !== EXPECTED_OPERATION_COUNT) {
    throw new TypeError(
      `Renderer handoff must contain ${EXPECTED_OPERATION_COUNT} operations, received ${operations.length}`,
    );
  }

  const operationIds = new Set(operations.map(({ operationId }) => operationId));
  const sampleIds = Object.keys(NODE_CODE_SAMPLES);
  const unexpectedSampleIds = sampleIds.filter((operationId) => !operationIds.has(operationId));
  if (sampleIds.length !== operations.length || unexpectedSampleIds.length > 0) {
    throw new TypeError(
      `Renderer sample inventory does not match REST operations: unexpected ${JSON.stringify(unexpectedSampleIds)}`,
    );
  }

  const handoff = {
    version: 1,
    restDigest: digestYamlArtifact(openApi),
    operations: operations.map(({ operationId, method, path }) => {
      const sample = NODE_CODE_SAMPLES[operationId];
      if (sample === undefined) {
        throw new TypeError(`Renderer sample is missing for operation ${operationId}`);
      }
      const operationKey = `${method.toUpperCase()} ${path}`;
      if (NODE_OPERATION_KEYS[operationId] !== operationKey) {
        throw new TypeError(`Renderer sample operation key is stale for ${operationId}`);
      }
      if (sample.lang !== NODE_SAMPLE_LANGUAGE) {
        throw new TypeError(`Renderer sample language is inconsistent for ${operationId}`);
      }

      return {
        operationId,
        samples: [
          {
            label: sample.label,
            language: sample.lang,
            sourceHash: sha256Hex(Buffer.from(sample.source, "utf8")),
          },
        ],
      };
    }),
  };
  const source = canonicalizeJson(handoff);

  return {
    source: source.toString("utf8"),
    digest: sha256Hex(source),
  };
}

async function readOptional(path) {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if (error !== null && typeof error === "object" && error.code === "ENOENT") return undefined;
    throw error;
  }
}

async function run(check) {
  const expectedReference = await generateApiReference();
  const expectedHandoff = await generateRendererHandoff();
  const outputs = [
    [outputPath, expectedReference],
    [rendererHandoffPath, expectedHandoff.source],
    [rendererHandoffDigestPath, `${expectedHandoff.digest}\n`],
  ];

  if (check) {
    for (const [path, expected] of outputs) {
      const actual = await readOptional(resolve(repositoryRoot, path));
      if (actual !== expected) throw new TypeError(`${path} is stale`);
    }
    return;
  }

  for (const [path, expected] of outputs) {
    const absoluteOutput = resolve(repositoryRoot, path);
    await mkdir(dirname(absoluteOutput), { recursive: true });
    await writeFile(absoluteOutput, expected, "utf8");
  }
}

async function main() {
  const arguments_ = process.argv.slice(2);
  if (arguments_.some((argument) => argument !== "--check") || arguments_.length > 1) {
    throw new TypeError("Usage: node scripts/generate-docs.mjs [--check]");
  }
  await run(arguments_[0] === "--check");
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  main().catch((error) => {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`generate-docs: ${message}\n`);
    process.exitCode = 1;
  });
}
